### Import

In [1]:
import os; import pandas as pd
pd.options.display.float_format = '{:.3f}'.format
pd.set_option("display.max_rows", None)
pd.set_option("display.max_columns", None)
import numpy as np; import matplotlib.pyplot as plt
import gurobipy as gp; from gurobipy import GRB
from itertools import product; from tqdm import tqdm
import importlib
import functions_utils; import functions_data
import functions_optimize; import functions_eval
importlib.reload(functions_data); importlib.reload(functions_optimize)
importlib.reload(functions_eval); importlib.reload(functions_utils)
from functions_utils import *; from functions_data import *
from functions_optimize import *; from functions_eval import *
import time

S = 20
LEVEL = "high"
SEED = 42

generation_data, I, T = load_generation_data(date_filter="2022-07-18")
R, P_RT, K, K0, M1, M2 = load_parameters(I, T, generation_data, S, LEVEL, SEED)
P_DA, P_PN = load_price_data(P_RT)

✅ 총 5개 파일을 불러왔습니다: 1201.csv, 137.csv, 401.csv, 524.csv, 89.csv
📊 데이터 Shape: I=5, T=24, S=20
✅ 시뮬레이션 초기화 완료: S=20, Randomness='high', Random Seed=42, M1=763.86, M2=2075.61

### Linear Decision Rule (Individual Optimization)

In [ ]:
model = gp.Model("individual_LDR")
model.setParam("MIPGap", 1e-5)
model.setParam(GRB.Param.PoolSearchMode, 2)
model.setParam(GRB.Param.PoolSolutions, 1)

x_ind = model.addVars(I, T, vtype=GRB.CONTINUOUS, lb=0, name="x")
yp_ind = model.addVars(I, T, S, vtype=GRB.CONTINUOUS, lb=0, name="yp")
ym_ind = model.addVars(I, T, S, vtype=GRB.CONTINUOUS, lb=0, name="ym")
z_ind = model.addVars(I, T + 1, S, vtype=GRB.CONTINUOUS, lb=0, name="z")
zc_ind = model.addVars(I, T, S, vtype=GRB.CONTINUOUS, lb=0, name="zc")
zd_ind = model.addVars(I, T, S, vtype=GRB.CONTINUOUS, lb=0, name="zd")
    
phi1_ind = model.addVars(I, T, S, vtype=GRB.BINARY, name="phi1") ; phi2_ind = model.addVars(I, T, S, vtype=GRB.BINARY, name="phi2") ; phi3_ind = model.addVars(I, T, S, vtype=GRB.BINARY, name="phi3")

# LDR 계수 변수들
zc0_ind = model.addVars(I, T, vtype=GRB.CONTINUOUS, name="zc0") ; zc1_ind = model.addVars(I, T, vtype=GRB.CONTINUOUS, name="zc1") ; zc2_ind = model.addVars(I, T, vtype=GRB.CONTINUOUS, name="zc2")
zd0_ind = model.addVars(I, T, vtype=GRB.CONTINUOUS, name="zd0") ; zd1_ind = model.addVars(I, T, vtype=GRB.CONTINUOUS, name="zd1") ; zd2_ind = model.addVars(I, T, vtype=GRB.CONTINUOUS, name="zd2")

model.update()

# obj = (gp.quicksum(P_DA[t] * x_ind[i, t] for i in range(I) for t in range(T)) + 
#        gp.quicksum((1/S) * (P_RT[t, s] * yp_ind[i, t, s] - P_PN[t, s] * ym_ind[i, t, s]) for i in range(I) for t in range(T) for s in range(S)))
# model.setObjective(obj, GRB.MAXIMIZE)

# # Quadratic Regularization
obj = (gp.quicksum(P_DA[t] * x_ind[i, t] for i in range(I) for t in range(T)) + 
       gp.quicksum((1/S) * (P_RT[t, s] * yp_ind[i, t, s] - P_PN[t, s] * ym_ind[i, t, s]) for i in range(I) for t in range(T) for s in range(S)))
reg = gp.quicksum(x_ind[i, t] * x_ind[i, t] for i in range(I) for t in range(T))
epsilon = 1e-7
regularized_obj = obj - epsilon * reg
model.setObjective(regularized_obj, GRB.MAXIMIZE)

for i, t, s in product(range(I), range(T), range(S)):
    # model.addConstr(zc_ind[i, t, s] == zc0_ind[i, t] + zc1_ind[i, t] * R[i, t, s])
    # model.addConstr(zd_ind[i, t, s] == zd0_ind[i, t] + zd1_ind[i, t] * R[i, t, s])
    # model.addConstr(zc_ind[i, t, s] == zc0_ind[i, t] + zc1_ind[i, t] * P_RT[t, s])
    # model.addConstr(zd_ind[i, t, s] == zd0_ind[i, t] + zd1_ind[i, t] * P_RT[t, s])
    # model.addConstr(zc_ind[i, t, s] == zc0_ind[i, t] + zc1_ind[i, t] * P_PN[t, s])
    # model.addConstr(zd_ind[i, t, s] == zd0_ind[i, t] + zd1_ind[i, t] * P_PN[t, s])
    model.addConstr(zc_ind[i, t, s] == zc0_ind[i, t] + zc1_ind[i, t] * (P_RT[t, s] - P_DA[t]))
    model.addConstr(zd_ind[i, t, s] == zd0_ind[i, t] + zd1_ind[i, t] * (P_RT[t, s] - P_DA[t]))
    # model.addConstr(zc_ind[i, t, s] == zc0_ind[i, t] + zc1_ind[i, t] * (P_PN[t, s] - P_DA[t]))
    # model.addConstr(zd_ind[i, t, s] == zd0_ind[i, t] + zd1_ind[i, t] * (P_PN[t, s] - P_DA[t]))
    # model.addConstr(zc_ind[i, t, s] == zc0_ind[i, t] + zc1_ind[i, t] * R[i, t, s] + zc2_ind[i, t] * P_RT[t, s])
    # model.addConstr(zd_ind[i, t, s] == zd0_ind[i, t] + zd1_ind[i, t] * R[i, t, s] + zd2_ind[i, t] * P_RT[t, s])
    # model.addConstr(zc_ind[i, t, s] == zc0_ind[i, t] + zc1_ind[i, t] * R[i, t, s] + zc2_ind[i, t] * P_PN[t, s])
    # model.addConstr(zd_ind[i, t, s] == zd0_ind[i, t] + zd1_ind[i, t] * R[i, t, s] + zd2_ind[i, t] * P_PN[t, s])
    # model.addConstr(zc_ind[i, t, s] == zc0_ind[i, t] + zc1_ind[i, t] * R[i, t, s] + zc2_ind[i, t] * (P_RT[t, s] - P_DA[t]))
    # model.addConstr(zd_ind[i, t, s] == zd0_ind[i, t] + zd1_ind[i, t] * R[i, t, s] + zd2_ind[i, t] * (P_RT[t, s] - P_DA[t]))


for i, t, s in product(range(I), range(T), range(S)):
    model.addConstr(R[i, t, s] - x_ind[i, t] == yp_ind[i, t, s] - ym_ind[i, t, s] + zc_ind[i, t, s] - zd_ind[i, t, s])
    model.addConstr(R[i, t, s] + zd_ind[i, t, s] >= yp_ind[i, t, s] + zc_ind[i, t, s])
    model.addConstr(zd_ind[i, t, s] <= z_ind[i, t, s])
    model.addConstr(zc_ind[i, t, s] <= K[i] - z_ind[i, t, s])
    model.addConstr(z_ind[i, t, s] <= K[i])
    model.addConstr(z_ind[i, t + 1, s] == z_ind[i, t, s] + 0.9 * zc_ind[i, t, s] - zd_ind[i, t, s] / 0.9)
        
    model.addConstr(yp_ind[i, t, s] <= M1 * phi1_ind[i, t, s]) ; model.addConstr(ym_ind[i, t, s] <= M1 * (1 - phi1_ind[i, t, s]))
    model.addConstr(ym_ind[i, t, s] <= M1 * phi2_ind[i, t, s]) ; model.addConstr(zc_ind[i, t, s] <= M1 * (1 - phi2_ind[i, t, s]))
    model.addConstr(zc_ind[i, t, s] <= M1 * phi3_ind[i, t, s]) ; model.addConstr(zd_ind[i, t, s] <= M1 * (1 - phi3_ind[i, t, s]))
    
for i, s in product(range(I), range(S)): model.addConstr(z_ind[i, 0, s] == K0[i])

model.optimize()

Set parameter MIPGap to value 1e-05
Set parameter PoolSearchMode to value 2

Set parameter PoolSolutions to value 2
Gurobi Optimizer version 12.0.2 build v12.0.2rc0 (win64 - Windows 11.0 (26100.2))

CPU model: 13th Gen Intel(R) Core(TM) i9-13900K, instruction set [SSE2|AVX|AVX2]
Thread count: 24 physical cores, 32 logical processors, using up to 32 threads

Non-default parameters:
MIPGap  1e-05
PoolSolutions  2
PoolSearchMode  2

Optimize a model with 33700 rows, 20140 columns and 84100 nonzeros
Model fingerprint: 0xa1df85fd
Model has 120 quadratic objective terms
Variable types: 12940 continuous, 7200 integer (7200 binary)
Coefficient statistics:
  Matrix range     [5e-03, 8e+02]
  Objective range  [2e+00, 2e+02]
  QObjective range [2e-07, 2e-07]
  Bounds range     [1e+00, 1e+00]
  RHS range        [8e-02, 8e+02]
Found heuristic solution: objective 868401.91111
Presolve removed 12153 rows and 4299 columns
Presolve time: 0.22s
Presolved: 21547 rows, 15841 columns, 57392 nonzeros
Presolved model has 120 quadratic objective terms
Variable types: 8641 continuous, 7200 integer (7200 binary)

Root relaxation: objective 1.638114e+06, 52692 iterations, 1.66 seconds (1.38 work units)

    Nodes    |    Current Node    |     Objective Bounds      |     Work
 Expl Unexpl |  Obj  Depth IntInf | Incumbent    BestBd   Gap | It/Node Time

     0     0 1638113.73    0 1602 868401.911 1638113.73  88.6%     -    2s
H    0     0                    868401.91111 1638113.73  88.6%     -    2s
     0     0 1633725.63    0 1364 868401.911 1633725.63  88.1%     -    2s
     0     0 1632575.11    0 1256 868401.911 1632575.11  88.0%     -    2s
     0     0 1632514.61    0 1228 868401.911 1632514.61  88.0%     -    2s
     0     0 1632436.16    0 1224 868401.911 1632436.16  88.0%     -    2s
     0     0 1632432.46    0 1224 868401.911 1632432.46  88.0%     -    2s
     0     0 1632432.46    0  898 868401.911 1632432.46  88.0%     -    3s
H    0     0                    869097.62016 1632432.46  87.8%     -    3s
     0     0 1632432.46    0  858 869097.620 1632432.46  87.8%     -    3s
     0     0 1632432.46    0  883 869097.620 1632432.46  87.8%     -    3s
     0     0 1632432.46    0  887 869097.620 1632432.46  87.8%     -    3s
     0     0 1632401.56    0  643 869097.620 1632401.56  87.8%     -    3s
     0     0 1632401.56    0  623 869097.620 1632401.56  87.8%     -    4s
     0     0 1632401.56    0  624 869097.620 1632401.56  87.8%     -    4s
     0     0 1632401.56    0  508 869097.620 1632401.56  87.8%     -    4s
     0     0 1632401.56    0  487 869097.620 1632401.56  87.8%     -    4s
     0     0 1632401.56    0  488 869097.620 1632401.56  87.8%     -    4s
     0     0 1632401.56    0  361 869097.620 1632401.56  87.8%     -    4s
     0     0 1632401.56    0  358 869097.620 1632401.56  87.8%     -    4s
     0     0 1632401.56    0  355 869097.620 1632401.56  87.8%     -    4s
     0     0 1632401.56    0  354 869097.620 1632401.56  87.8%     -    4s
     0     0 1632401.56    0  354 869097.620 1632401.56  87.8%     -    4s
     0     0 1632401.56    0  353 869097.620 1632401.56  87.8%     -    4s
H    0     0                    874215.48902 1632401.56  86.7%     -    4s
H    0     0                    874894.42220 1632401.56  86.6%     -    4s
     0     0 1632361.87    0  370 874894.422 1632361.87  86.6%     -    4s
H    0     0                    874895.05545 1632357.78  86.6%     -    4s
H    0     0                    876033.05544 1632357.78  86.3%     -    4s
     0     0 1632352.57    0  332 876033.055 1632352.57  86.3%     -    4s
     0     0 1632333.05    0  332 876033.055 1632333.05  86.3%     -    4s
     0     0 1632330.32    0  332 876033.055 1632330.32  86.3%     -    4s
     0     0 1632305.60    0  315 876033.055 1632305.60  86.3%     -    5s
     0     0 1632295.88    0  298 876033.055 1632295.88  86.3%     -    5s
     0     0 1632295.88    0  298 876033.055 1632295.88  86.3%     -    5s
H    0     0                    883786.52849 1632295.88  84.7%     -    5s
     0     0 1632282.53    0  295 883786.528 1632282.53  84.7%     -    5s
H    0     0                    883786.52849 1632277.66  84.7%     -    5s
     0     0 1632277.66    0  317 883786.528 1632277.66  84.7%     -    5s
H    0     0                    900923.11394 1632277.66  81.2%     -    5s
     0     0 1632276.85    0  312 900923.114 1632276.85  81.2%     -    5s
H    0     0                    939801.07036 1632251.01  73.7%     -    5s
H    0     0                    940079.80102 1632251.01  73.6%     -    5s
H    0     0                    957638.65413 1632251.01  70.4%     -    5s
H    0     0                    969332.28761 1632251.01  68.4%     -    5s
H    0     0                    970726.75944 1632251.01  68.1%     -    5s
H    0     0                    1050112.8008 1632251.01  55.4%     -    5s
H    0     0                    1628022.1168 1632251.01  0.26%     -    6s
     0     2 1632251.01    0  313 1628022.12 1632251.01  0.26%     -    6s
H   66   120                    1630352.5067 1632178.91  0.11%   247    7s
H   97   120                    1630531.7183 1632178.91  0.10%   191    7s
  1459  1052 1631949.74   47  164 1630531.72 1632178.91  0.10%  47.7   10s
  2508  1856 1631078.32   69  118 1630531.72 1632178.91  0.10%  40.8   15s
* 2528  1634             175    1630597.4134 1632178.91  0.10%  40.6   15s
H 2814  1777                    1631070.9181 1632178.91  0.07%  53.2   16s
H 3095  1264                    1631798.6108 1632178.91  0.02%  50.1   17s
H 3095   600                    1632097.9322 1632178.91  0.00%  50.1   17s
H 3097   482                    1632097.9323 1632178.91  0.00%  50.1   20s

Cutting planes:
  Gomory: 27
  Cover: 235
  Implied bound: 316
  Clique: 207
  MIR: 369
  Mixing: 2
  Flow cover: 1045
  RLT: 220
  Relax-and-lift: 366
  BQP: 5
  PSD: 182

Explored 3121 nodes (269634 simplex iterations) in 24.37 seconds (17.29 work units)
Thread count was 32 (of 32 available processors)

Solution count 2: 1.6321e+06 1.6321e+06
No other solutions better than 1.6321e+06

Optimal solution found (tolerance 1.00e-05)
Best objective 1.632097932277e+06, best bound 1.632102797405e+06, gap 0.0003%

In [ ]:
if model.status == GRB.OPTIMAL:
    num_solutions = model.SolCount
    print(f"\n--- Solution Pool Analysis ---")
    print(f"Found {num_solutions} solutions in the pool.")

    if num_solutions > 1:
        best_obj = model.objVal
        print(f"Best objective value: {best_obj:.8f}\n")

        for i in range(num_solutions):
            model.setParam(GRB.Param.SolutionNumber, i)
            pool_obj = model.PoolObjVal
            diff = best_obj - pool_obj
            
            print(f"Solution {i}: Objective = {pool_obj},  Difference from best = {diff}")

    model.setParam(GRB.Param.SolutionNumber, 0)
    
    x_ind = np.array([[x_ind[i, t].X for t in range(T)] for i in range(I)])
    yp_ind = np.array([[[yp_ind[i, t, s].X for s in range(S)] for t in range(T)] for i in range(I)]) ; ym_ind = np.array([[[ym_ind[i, t, s].X for s in range(S)] for t in range(T)] for i in range(I)])
    zc_ind = np.array([[[zc_ind[i, t, s].X for s in range(S)] for t in range(T)] for i in range(I)]) ; zd_ind = np.array([[[zd_ind[i, t, s].X for s in range(S)] for t in range(T)] for i in range(I)])
    z_ind = np.array([[[z_ind[i, t, s].X for s in range(S)] for t in range(T+1)] for i in range(I)]) ; original_objval = model.objVal
    phi1_ind = np.array([[[phi1_ind[i, t, s].X for s in range(S)] for t in range(T)] for i in range(I)]) ; phi2_ind = np.array([[[phi2_ind[i, t, s].X for s in range(S)] for t in range(T)] for i in range(I)])
    phi3_ind = np.array([[[phi3_ind[i, t, s].X for s in range(S)] for t in range(T)] for i in range(I)])
    
    zc0_ind = np.array([[zc0_ind[i, t].X for t in range(T)] for i in range(I)]) ; zc1_ind = np.array([[zc1_ind[i, t].X for t in range(T)] for i in range(I)]) ; zc2_ind = np.array([[zc2_ind[i, t].X for t in range(T)] for i in range(I)])
    zd0_ind = np.array([[zd0_ind[i, t].X for t in range(T)] for i in range(I)]) ; zd1_ind = np.array([[zd1_ind[i, t].X for t in range(T)] for i in range(I)]) ; zd2_ind = np.array([[zd2_ind[i, t].X for t in range(T)] for i in range(I)])
    OBJ_IND = model.objVal

--- Solution Pool Analysis ---
Found 2 solutions in the pool.
Best objective value: 1632097.93227715

Solution 0: Objective = 1632097.9322771467,  Difference from best = 0.0
Solution 1: Objective = 1632097.932249691,  Difference from best = 2.745562233030796e-05

In [21]:
for i, t, s in product(range(I), range(T), range(S)):
    if yp_ind[i, t, s] != 0 and ym_ind[i, t, s] != 0: print("[VIOLATION] YP-YM", i, t, s, yp_ind[i,t,s], ym_ind[i,t,s])
    if ym_ind[i, t, s] != 0 and zc_ind[i, t, s] != 0: print("[VIOLATION] YM-ZC", i, t, s, ym_ind[i,t,s], zc_ind[i,t,s])
    if zc_ind[i, t, s] != 0 and zd_ind[i, t, s] != 0: print("[VIOLATION] ZC-ZD", i, t, s, zc_ind[i,t,s], zd_ind[i,t,s])

In [22]:
header = (f"{'t':>2} | {'R':>8} {'x':>8} {'y+':>8} {'y-':>8} {'zc':>8} {'zd':>8} {'z':>8}\n" + "-" * 70)
print("\n[Individual]") ; print(header)
for t in range(7, 22):
    # R_avg = np.mean([R[:, t, s].sum() for s in range(S)]) ; x_sum = x_ind[:, t].sum()
    # yp_avg = np.mean([yp_ind[:, t, s].sum() for s in range(S)]) ; ym_avg = np.mean([ym_ind[:, t, s].sum() for s in range(S)])
    # zc_avg = np.mean([zc_ind[:, t, s].sum() for s in range(S)]) ; zd_avg = np.mean([zd_ind[:, t, s].sum() for s in range(S)]) 
    # z_avg = np.mean([z_ind[:, t, s].sum() for s in range(S)])

    i=0
    R_avg = np.mean([R[i, t, s] for s in range(S)]) ; x_sum = x_ind[i, t]
    yp_avg = np.mean([yp_ind[i, t, s] for s in range(S)]) ; ym_avg = np.mean([ym_ind[i, t, s] for s in range(S)])
    zc_avg = np.mean([zc_ind[i, t, s] for s in range(S)]) ; zd_avg = np.mean([zd_ind[i, t, s] for s in range(S)]) 
    z_avg = np.mean([z_ind[i, t, s] for s in range(S)])

    print(f"{t:>2} | {R_avg:>8.2f} {x_sum:>8.2f} {yp_avg:>8.2f} {ym_avg:>8.2f} {zc_avg:>8.2f} {zd_avg:>8.2f} {z_avg:>8.2f}")

[Individual]
 t |        R        x       y+       y-       zc       zd        z
----------------------------------------------------------------------
 7 |     0.00     0.00     0.00     0.00     0.00     0.00     0.00
 8 |    15.70     0.00     3.15     0.00    12.55     0.00     0.00
 9 |     3.87     0.00     0.00     0.00     3.87     0.00    11.30
10 |    33.49     0.00    18.20     0.00    15.29     0.00    14.78
11 |    60.71     0.00    35.83     0.00    24.88     0.00    28.54
12 |   166.49     0.00   134.69     0.00    31.80     0.00    50.93
13 |   256.48     0.00   304.77     0.00     0.00    48.29    79.55
14 |   163.84     0.00   109.89     0.00    53.95     0.00    25.89
15 |   160.46     0.00   220.73     0.00     0.00    60.27    74.45
16 |    18.71     7.13    11.88     0.31     0.00     0.00     7.48
17 |     0.00     0.00     0.00     0.00     0.00     0.00     7.48
18 |    67.36    17.16    50.20     0.00     0.00     0.00     7.48
19 |    67.32    36.55    31.97     1.21     0.00     0.00     7.48
20 |    41.98    26.26    17.84     2.12     0.00     0.00     7.48
21 |     6.81     2.64     4.21     0.04     0.00     0.00     7.48

In [ ]:
print("\n=== 모든 LDR 계수 (i, t별) ===")
print("Individual | Time | Variable | 상수항    | R계수    ")
print("-" * 50)

for t in range(9,20):
    for i in range(I):
        print(f"{i:10d} | {t:4d} | zc       | {zc0_ind[i,t]:8.4f} | {zc1_ind[i,t]:7.4f}")
        print(f"{i:10d} | {t:4d} | zd       | {zd0_ind[i,t]:8.4f} | {zd1_ind[i,t]:7.4f}")
        print(f"{i:10d} | {t:4d} | x (1st)  | {x_ind[i,t]:8.4f} |    -    ")
        print("-" * 50)

=== 모든 LDR 계수 (i, t별) ===
Individual | Time | Variable | 상수항    | R계수
--------------------------------------------------
         0 |    9 | zc       |   5.8829 |  0.0774
         0 |    9 | zd       |   0.0000 |  0.0000
         0 |    9 | x (1st)  |   0.0000 |    -
--------------------------------------------------
         1 |    9 | zc       |  18.0606 |  0.0000
         1 |    9 | zd       |   0.0000 |  0.0000
         1 |    9 | x (1st)  |   0.0001 |    -
--------------------------------------------------
         2 |    9 | zc       |  18.6331 |  0.0000
         2 |    9 | zd       |   0.0000 |  0.0000
         2 |    9 | x (1st)  |   0.0000 |    -
--------------------------------------------------
         3 |    9 | zc       |   5.5543 |  0.0000
         3 |    9 | zd       |   0.0000 |  0.0000
         3 |    9 | x (1st)  |   0.0000 |    -
--------------------------------------------------
         4 |    9 | zc       |   6.0872 |  0.0000
         4 |    9 | zd       |   0.0000 |  0.0000
         4 |    9 | x (1st)  |   0.0000 |    -
--------------------------------------------------
         0 |   10 | zc       |  20.7922 |  0.2150
         0 |   10 | zd       |   0.0000 |  0.0000
         0 |   10 | x (1st)  |  -0.0000 |    -
--------------------------------------------------
         1 |   10 | zc       |  40.6763 |  0.0000
         1 |   10 | zd       |   0.0000 |  0.0000
         1 |   10 | x (1st)  |   0.0001 |    -
--------------------------------------------------
         2 |   10 | zc       |  37.9442 |  0.0000
         2 |   10 | zd       |   0.0000 |  0.0000
         2 |   10 | x (1st)  |  -0.0000 |    -
--------------------------------------------------
         3 |   10 | zc       |  17.7276 |  0.0000
         3 |   10 | zd       |   0.0000 |  0.0000
         3 |   10 | x (1st)  |   0.0001 |    -
--------------------------------------------------
         4 |   10 | zc       |  12.2746 |  0.0000
         4 |   10 | zd       |   0.0000 |  0.0000
         4 |   10 | x (1st)  |   0.0001 |    -
--------------------------------------------------
         0 |   11 | zc       |  26.8611 |  0.2278
         0 |   11 | zd       |   0.0000 |  0.0000
         0 |   11 | x (1st)  |   0.0000 |    -
--------------------------------------------------
         1 |   11 | zc       |  43.8522 |  0.0000
         1 |   11 | zd       |   0.0000 |  0.0000
         1 |   11 | x (1st)  |   0.0000 |    -
--------------------------------------------------
         2 |   11 | zc       |  42.6871 |  0.0000
         2 |   11 | zd       |   0.0000 |  0.0000
         2 |   11 | x (1st)  |  10.9941 |    -
--------------------------------------------------
         3 |   11 | zc       |  40.1131 |  0.0000
         3 |   11 | zd       |   0.0000 |  0.0000
         3 |   11 | x (1st)  |   0.0000 |    -
--------------------------------------------------
         4 |   11 | zc       |  29.0621 |  0.0000
         4 |   11 | zd       |   0.0000 |  0.0000
         4 |   11 | x (1st)  |   0.0000 |    -
--------------------------------------------------
         0 |   12 | zc       |  31.7994 |  0.0000
         0 |   12 | zd       |   0.0000 |  0.0000
         0 |   12 | x (1st)  |   0.0000 |    -
--------------------------------------------------
         1 |   12 | zc       |   5.1459 |  0.0000
         1 |   12 | zd       |   0.0000 |  0.0000
         1 |   12 | x (1st)  |   0.0000 |    -
--------------------------------------------------
         2 |   12 | zc       |   4.2687 |  0.0000
         2 |   12 | zd       |   0.0000 |  0.0000
         2 |   12 | x (1st)  |   0.0000 |    -
--------------------------------------------------
         3 |   12 | zc       |  41.9695 |  0.0000
         3 |   12 | zd       |   0.0000 |  0.0000
         3 |   12 | x (1st)  |   0.0000 |    -
--------------------------------------------------
         4 |   12 | zc       |  25.1476 |  0.0000
         4 |   12 | zd       |   0.0000 |  0.0000
         4 |   12 | x (1st)  |   0.0000 |    -
--------------------------------------------------
         0 |   13 | zc       |   0.0000 |  0.0000
         0 |   13 | zd       |  48.2891 |  0.0000
         0 |   13 | x (1st)  |   0.0000 |    -
--------------------------------------------------
         1 |   13 | zc       |   0.0000 |  0.0000
         1 |   13 | zd       |  63.1147 |  0.0000
         1 |   13 | x (1st)  |   0.0000 |    -
--------------------------------------------------
         2 |   13 | zc       |   0.0000 |  0.0000
         2 |   13 | zd       |  83.8860 |  0.0000
         2 |   13 | x (1st)  |   0.0000 |    -
--------------------------------------------------
         3 |   13 | zc       |   0.0000 |  0.0000
         3 |   13 | zd       |  86.2227 |  0.0000
         3 |   13 | x (1st)  |   0.0000 |    -
--------------------------------------------------
         4 |   13 | zc       |   0.0000 |  0.0000
         4 |   13 | zd       |   9.6177 |  0.0000
         4 |   13 | x (1st)  |   0.0000 |    -
--------------------------------------------------
         0 |   14 | zc       |  61.8567 |  0.1422
         0 |   14 | zd       |   0.0000 |  0.0000
         0 |   14 | x (1st)  |   0.0000 |    -
--------------------------------------------------
         1 |   14 | zc       |  70.6421 |  0.0000
         1 |   14 | zd       |   0.0000 |  0.0000
         1 |   14 | x (1st)  |   0.0002 |    -
--------------------------------------------------
         2 |   14 | zc       |  93.6336 |  0.0000
         2 |   14 | zd       |   0.0000 |  0.0000
         2 |   14 | x (1st)  |   0.0000 |    -
--------------------------------------------------
         3 |   14 | zc       | 100.0000 |  0.0000
         3 |   14 | zd       |   0.0000 |  0.0000
         3 |   14 | x (1st)  |   4.3590 |    -
--------------------------------------------------
         4 |   14 | zc       |  44.1604 |  0.0000
         4 |   14 | zd       |   0.0000 |  0.0000
         4 |   14 | x (1st)  |   0.0000 |    -
--------------------------------------------------
         0 |   15 | zc       |   0.0000 |  0.0000
         0 |   15 | zd       |  60.2704 |  0.0000
         0 |   15 | x (1st)  |   0.0000 |    -
--------------------------------------------------
         1 |   15 | zc       |   0.0000 |  0.0000
         1 |   15 | zd       |  83.6422 |  0.0000
         1 |   15 | x (1st)  |   0.0000 |    -
--------------------------------------------------
         2 |   15 | zc       |   0.0000 |  0.0000
         2 |   15 | zd       |  81.5730 |  0.0000
         2 |   15 | x (1st)  |   0.0000 |    -
--------------------------------------------------
         3 |   15 | zc       |   0.0000 |  0.0000
         3 |   15 | zd       |  81.0000 |  0.0000
         3 |   15 | x (1st)  |   0.0000 |    -
--------------------------------------------------
         4 |   15 | zc       |   0.0000 |  0.0000
         4 |   15 | zd       |  86.0256 |  0.0000
         4 |   15 | x (1st)  |   0.0000 |    -
--------------------------------------------------
         0 |   16 | zc       |   0.0000 |  0.0000
         0 |   16 | zd       |   0.0000 |  0.0000
         0 |   16 | x (1st)  |   7.1307 |    -
--------------------------------------------------
         1 |   16 | zc       |   0.0000 |  0.0000
         1 |   16 | zd       |   0.0000 |  0.0000
         1 |   16 | x (1st)  |  71.4941 |    -
--------------------------------------------------
         2 |   16 | zc       |   0.0000 |  0.0000
         2 |   16 | zd       |   0.0000 |  0.0000
         2 |   16 | x (1st)  |  67.2658 |    -
--------------------------------------------------
         3 |   16 | zc       |   0.0000 |  0.0000
         3 |   16 | zd       |   0.0000 |  0.0000
         3 |   16 | x (1st)  | 237.7886 |    -
--------------------------------------------------
         4 |   16 | zc       |   0.0000 |  0.0000
         4 |   16 | zd       |   0.0000 |  0.0000
         4 |   16 | x (1st)  |  17.3711 |    -
--------------------------------------------------
         0 |   17 | zc       |   0.0000 |  0.0000
         0 |   17 | zd       |   0.0000 | -0.0000
         0 |   17 | x (1st)  |   0.0000 |    -
--------------------------------------------------
         1 |   17 | zc       |   0.0000 |  0.0000
         1 |   17 | zd       |   0.0000 |  0.0000
         1 |   17 | x (1st)  |   0.0000 |    -
--------------------------------------------------
         2 |   17 | zc       |   0.0000 |  0.0000
         2 |   17 | zd       |   0.0000 |  0.0000
         2 |   17 | x (1st)  |   0.0000 |    -
--------------------------------------------------
         3 |   17 | zc       |   0.0000 |  0.0000
         3 |   17 | zd       |   0.0000 |  0.0000
         3 |   17 | x (1st)  |   0.0000 |    -
--------------------------------------------------
         4 |   17 | zc       |   0.0000 |  0.0000
         4 |   17 | zd       |   0.0000 |  0.0000
         4 |   17 | x (1st)  |   0.0000 |    -
--------------------------------------------------
         0 |   18 | zc       |   0.0000 |  0.0000
         0 |   18 | zd       |   0.0000 |  0.0000
         0 |   18 | x (1st)  |  17.1580 |    -
--------------------------------------------------
         1 |   18 | zc       |   0.0000 |  0.0000
         1 |   18 | zd       |   0.0000 |  0.0000
         1 |   18 | x (1st)  |  21.9846 |    -
--------------------------------------------------
         2 |   18 | zc       |   0.0000 |  0.0000
         2 |   18 | zd       |   0.0000 |  0.0000
         2 |   18 | x (1st)  |  31.6286 |    -
--------------------------------------------------
         3 |   18 | zc       |   0.0000 |  0.0000
         3 |   18 | zd       |   0.0000 |  0.0000
         3 |   18 | x (1st)  |  45.7100 |    -
--------------------------------------------------
         4 |   18 | zc       |   0.0000 |  0.0000
         4 |   18 | zd       |   0.0000 |  0.0000
         4 |   18 | x (1st)  |   8.9788 |    -
--------------------------------------------------
         0 |   19 | zc       |   0.0000 |  0.0000
         0 |   19 | zd       |   0.0000 |  0.0000
         0 |   19 | x (1st)  |  36.5517 |    -
--------------------------------------------------
         1 |   19 | zc       |   0.0000 |  0.0000
         1 |   19 | zd       |   0.0000 |  0.0000
         1 |   19 | x (1st)  |  23.6168 |    -
--------------------------------------------------
         2 |   19 | zc       |   0.0000 |  0.0000
         2 |   19 | zd       |   0.0000 |  0.0000
         2 |   19 | x (1st)  |  28.2561 |    -
--------------------------------------------------
         3 |   19 | zc       |   0.0000 |  0.0000
         3 |   19 | zd       |   0.0000 |  0.0000
         3 |   19 | x (1st)  |  99.3385 |    -
--------------------------------------------------
         4 |   19 | zc       |   0.0000 |  0.0000
         4 |   19 | zd       |   0.0000 |  0.0000
         4 |   19 | x (1st)  |  26.2224 |    -
--------------------------------------------------

### Linear Decision Rule (Holistic Optimization)

In [7]:
model = gp.Model("holistic_LDR")
model.setParam("MIPGap", 1e-5)
model.setParam(GRB.Param.PoolSearchMode, 2)
model.setParam(GRB.Param.PoolSolutions, 2)

x_hol = model.addVars(I, T, vtype=GRB.CONTINUOUS, lb=0, name="x")
yp_hol = model.addVars(I, T, S, vtype=GRB.CONTINUOUS, lb=0, name="yp") ; ym_hol = model.addVars(I, T, S, vtype=GRB.CONTINUOUS, lb=0, name="ym")
dp_hol = model.addVars(I, T, S, vtype=GRB.CONTINUOUS, lb=0, name="dp") ; dm_hol = model.addVars(I, T, S, vtype=GRB.CONTINUOUS, lb=0, name="dm")
z_hol = model.addVars(I, T + 1, S, vtype=GRB.CONTINUOUS, lb=0, name="z")
zc_hol = model.addVars(I, T, S, vtype=GRB.CONTINUOUS, lb=0, name="zc") ; zd_hol = model.addVars(I, T, S, vtype=GRB.CONTINUOUS, lb=0, name="zd")
    
phi1_hol = model.addVars(I, T, S, vtype=GRB.BINARY, name="phi1") ; phi2_hol = model.addVars(I, T, S, vtype=GRB.BINARY, name="phi2") 
phi3_hol = model.addVars(I, T, S, vtype=GRB.BINARY, name="phi3") ; phi4_hol = model.addVars(I, T, S, vtype=GRB.BINARY, name="phi4")
phi5_hol = model.addVars(I, T, S, vtype=GRB.BINARY, name="phi5") ; phi6_hol = model.addVars(I, T, S, vtype=GRB.BINARY, name="phi6")
phi7_hol = model.addVars(I, T, S, vtype=GRB.BINARY, name="phi7")

zc0_hol = model.addVars(I, T, vtype=GRB.CONTINUOUS, name="zc0") ; zcR_hol = model.addVars(I, T, vtype=GRB.CONTINUOUS, name="zcR")
zd0_hol = model.addVars(I, T, vtype=GRB.CONTINUOUS, name="zd0") ; zdR_hol = model.addVars(I, T, vtype=GRB.CONTINUOUS, name="zdR")
zc2_hol = model.addVars(I, T, vtype=GRB.CONTINUOUS, name="zd2") ; zd2_hol = model.addVars(I, T, vtype=GRB.CONTINUOUS, name="zd2")

model.update()

# obj = (gp.quicksum(P_DA[t] * x_hol[i, t] for i in range(I) for t in range(T)) + 
#        gp.quicksum((1/S) * (P_RT[t, s] * yp_hol[i, t, s] - P_PN[t, s] * ym_hol[i, t, s]) for i in range(I) for t in range(T) for s in range(S)))
# model.setObjective(obj, GRB.MAXIMIZE)

# # Quadratic Regularization
obj = (gp.quicksum(P_DA[t] * x_hol[i, t] for i in range(I) for t in range(T)) + 
       gp.quicksum((1/S) * (P_RT[t, s] * yp_hol[i, t, s] - P_PN[t, s] * ym_hol[i, t, s]) for i in range(I) for t in range(T) for s in range(S)))
reg = gp.quicksum(x_hol[i, t] * x_hol[i, t] for i in range(I) for t in range(T))
epsilon = 1e-7
regularized_obj = obj - epsilon * reg
model.setObjective(regularized_obj, GRB.MAXIMIZE)

for i, t, s in product(range(I), range(T), range(S)):
    # model.addConstr(zc_hol[i, t, s] == zc0_hol[i, t] + zcR_hol[i, t] * R[i, t, s])
    # model.addConstr(zd_hol[i, t, s] == zd0_hol[i, t] + zdR_hol[i, t] * R[i, t, s])
    # model.addConstr(zc_hol[i, t, s] == zc0_hol[i, t] + zcR_hol[i, t] * P_RT[t, s])
    # model.addConstr(zd_hol[i, t, s] == zd0_hol[i, t] + zdR_hol[i, t] * P_RT[t, s])
    # model.addConstr(zc_hol[i, t, s] == zc0_hol[i, t] + zcR_hol[i, t] * P_PN[t, s])
    # model.addConstr(zd_hol[i, t, s] == zd0_hol[i, t] + zdR_hol[i, t] * P_PN[t, s])
    model.addConstr(zc_hol[i, t, s] == zc0_hol[i, t] + zcR_hol[i, t] * (P_RT[t, s] - P_DA[t]))
    model.addConstr(zd_hol[i, t, s] == zd0_hol[i, t] + zdR_hol[i, t] * (P_RT[t, s] - P_DA[t]))
    # model.addConstr(zc_hol[i, t, s] == zc0_hol[i, t] + zcR_hol[i, t] * (P_PN[t, s] - P_DA[t]))
    # model.addConstr(zd_hol[i, t, s] == zd0_hol[i, t] + zdR_hol[i, t] * (P_PN[t, s] - P_DA[t]))
    # model.addConstr(zc_hol[i, t, s] == zc0_hol[i, t] + zcR_hol[i, t] * R[i, t, s] + zc2_hol[i, t] * P_RT[t, s])
    # model.addConstr(zd_hol[i, t, s] == zd0_hol[i, t] + zdR_hol[i, t] * R[i, t, s] + zd2_hol[i, t] * P_RT[t, s])
    # model.addConstr(zc_hol[i, t, s] == zc0_hol[i, t] + zcR_hol[i, t] * R[i, t, s] + zc2_hol[i, t] * P_PN[t, s])
    # model.addConstr(zd_hol[i, t, s] == zd0_hol[i, t] + zdR_hol[i, t] * R[i, t, s] + zd2_hol[i, t] * P_PN[t, s])
    # model.addConstr(zc_hol[i, t, s] == zc0_hol[i, t] + zcR_hol[i, t] * R[i, t, s] + zc2_hol[i, t] * (P_RT[t, s] - P_DA[t]))
    # model.addConstr(zd_hol[i, t, s] == zd0_hol[i, t] + zdR_hol[i, t] * R[i, t, s] + zd2_hol[i, t] * (P_RT[t, s] - P_DA[t]))

for i, t, s in product(range(I), range(T), range(S)):
    model.addConstr(R[i, t, s] - x_hol[i, t] == yp_hol[i, t, s] - ym_hol[i, t, s] + dp_hol[i, t, s] - dm_hol[i, t, s] + zc_hol[i, t, s] - zd_hol[i, t, s])
    model.addConstr(R[i, t, s] + zd_hol[i, t, s] >= yp_hol[i, t, s] + dp_hol[i, t, s] + zc_hol[i, t, s])
    model.addConstr(zd_hol[i, t, s] <= z_hol[i, t, s])
    model.addConstr(zc_hol[i, t, s] <= K[i] - z_hol[i, t, s])
    model.addConstr(z_hol[i, t, s] <= K[i])
    model.addConstr(z_hol[i, t + 1, s] == z_hol[i, t, s] + 0.9 * zc_hol[i, t, s] - zd_hol[i, t, s] / 0.9)
        
    model.addConstr(yp_hol[i, t, s] <= M1 * phi1_hol[i, t, s]) ; model.addConstr(ym_hol[i, t, s] <= M1 * (1 - phi1_hol[i, t, s]))
    model.addConstr(dp_hol[i, t, s] <= M1 * phi2_hol[i, t, s]) ; model.addConstr(dm_hol[i, t, s] <= M1 * (1 - phi2_hol[i, t, s]))
    model.addConstr(yp_hol[i, t, s] <= M1 * phi3_hol[i, t, s]) ; model.addConstr(dm_hol[i, t, s] <= M1 * (1 - phi3_hol[i, t, s]))
    model.addConstr(ym_hol[i, t, s] <= M1 * phi4_hol[i, t, s]) ; model.addConstr(dp_hol[i, t, s] <= M1 * (1 - phi4_hol[i, t, s]))
    model.addConstr(ym_hol[i, t, s] <= M1 * phi5_hol[i, t, s]) ; model.addConstr(zc_hol[i, t, s] <= M1 * (1 - phi5_hol[i, t, s]))
    model.addConstr(dm_hol[i, t, s] <= M1 * phi6_hol[i, t, s]) ; model.addConstr(zc_hol[i, t, s] <= M1 * (1 - phi6_hol[i, t, s]))
    model.addConstr(zc_hol[i, t, s] <= M1 * phi7_hol[i, t, s]) ; model.addConstr(zd_hol[i, t, s] <= M1 * (1 - phi7_hol[i, t, s]))
    
for i, s in product(range(I), range(S)): model.addConstr(z_hol[i, 0, s] == K0[i])

balance_constraints = {}
for t, s in product(range(T), range(S)):
    balance_constraints[t, s] = model.addConstr(gp.quicksum(dp_hol[i, t, s] for i in range(I)) == gp.quicksum(dm_hol[i, t, s] for i in range(I)), name=f"balance_{t}_{s}")

model.optimize()

Set parameter MIPGap to value 1e-05
Set parameter PoolSearchMode to value 2
Set parameter PoolSolutions to value 2
Gurobi Optimizer version 12.0.2 build v12.0.2rc0 (win64 - Windows 11.0 (26100.2))

CPU model: 13th Gen Intel(R) Core(TM) i9-13900K, instruction set [SSE2|AVX|AVX2]
Thread count: 24 physical cores, 32 logical processors, using up to 32 threads

Non-default parameters:
MIPGap  1e-05
PoolSolutions  2
PoolSearchMode  2

Optimize a model with 53380 rows, 34540 columns and 134500 nonzeros
Model fingerprint: 0x5c550ae8
Model has 120 quadratic objective terms
Variable types: 17740 continuous, 16800 integer (16800 binary)
Coefficient statistics:
  Matrix range     [5e-03, 8e+02]
  Objective range  [2e+00, 2e+02]
  QObjective range [2e-07, 2e-07]
  Bounds range     [1e+00, 1e+00]
  RHS range        [8e-02, 8e+02]
Presolve removed 16146 rows and 5132 columns
Presolve time: 0.26s
Presolved: 37234 rows, 29408 columns, 95840 nonzeros
Presolved model has 120 quadratic objective terms
Variable types: 12608 continuous, 16800 integer (16800 binary)

Root simplex log...

Iteration    Objective       Primal Inf.    Dual Inf.      Time
   67374    4.8297604e+06   1.171615e+04   0.000000e+00      5s
  120283    3.8942148e+06   2.327769e+04   0.000000e+00     10s
  167717    2.7683283e+06   3.076504e+02   0.000000e+00     15s
  241332    1.6938050e+06   0.000000e+00   0.000000e+00     20s

Root relaxation: objective 1.693805e+06, 241332 iterations, 19.21 seconds (14.80 work units)

    Nodes    |    Current Node    |     Objective Bounds      |     Work
 Expl Unexpl |  Obj  Depth IntInf | Incumbent    BestBd   Gap | It/Node Time

     0     0 1693804.98    0 3120          - 1693804.98      -     -   19s
     0     0 1693547.05    0 2918          - 1693547.05      -     -   20s
     0     0 1693464.89    0 2866          - 1693464.89      -     -   21s
     0     0 1693436.94    0 2810          - 1693436.94      -     -   21s
     0     0 1693414.73    0 2781          - 1693414.73      -     -   21s
     0     0 1693414.73    0 2807          - 1693414.73      -     -   21s
     0     0 1693414.73    0 2807          - 1693414.73      -     -   21s
     0     0 1693140.46    0 2666          - 1693140.46      -     -   22s
     0     0 1693101.02    0 2643          - 1693101.02      -     -   23s
     0     0 1693098.11    0 2743          - 1693098.11      -     -   23s
     0     0 1693097.04    0 2756          - 1693097.04      -     -   23s
     0     0 1693097.01    0 2759          - 1693097.01      -     -   23s
     0     0 1692925.64    0 2698          - 1692925.64      -     -   26s
     0     0 1692864.29    0 2624          - 1692864.29      -     -   26s
     0     0 1692853.76    0 2662          - 1692853.76      -     -   27s
     0     0 1692853.68    0 2658          - 1692853.68      -     -   27s
     0     0 1692775.59    0 2605          - 1692775.59      -     -   30s
     0     0 1692585.14    0 2553          - 1692585.14      -     -   30s
     0     0 1692521.36    0 2534          - 1692521.36      -     -   31s
     0     0 1692520.65    0 2556          - 1692520.65      -     -   31s
     0     0 1692520.65    0 2562          - 1692520.65      -     -   31s
     0     0 1692289.53    0 2425          - 1692289.53      -     -   32s
     0     0 1692280.84    0 2516          - 1692280.84      -     -   32s
     0     0 1692280.84    0 2522          - 1692280.84      -     -   33s
     0     0 1692280.84    0 2521          - 1692280.84      -     -   33s
     0     0 1692280.84    0 2548          - 1692280.84      -     -   33s
     0     0 1692228.83    0 2443          - 1692228.83      -     -   34s
     0     0 1692220.62    0 2356          - 1692220.62      -     -   35s
     0     0 1692220.44    0 2371          - 1692220.44      -     -   35s
     0     0 1692220.44    0 2468          - 1692220.44      -     -   35s
     0     0 1692220.44    0 2468          - 1692220.44      -     -   35s
     0     0 1692220.44    0 2486          - 1692220.44      -     -   35s
     0     0 1692190.48    0 2395          - 1692190.48      -     -   36s
     0     0 1692190.41    0 2416          - 1692190.41      -     -   36s
     0     0 1692183.90    0 2431          - 1692183.90      -     -   36s
     0     0 1692183.90    0 2450          - 1692183.90      -     -   36s
     0     0 1692183.90    0 2353          - 1692183.90      -     -   37s
     0     0 1692183.90    0 2445          - 1692183.90      -     -   37s
     0     0 1692094.06    0 2393          - 1692094.06      -     -   38s
     0     0 1692094.06    0 2505          - 1692094.06      -     -   39s
     0     0 1692030.24    0 2535          - 1692030.24      -     -   39s
     0     0 1692030.24    0 2558          - 1692030.24      -     -   39s
     0     0 1692030.24    0 2325          - 1692030.24      -     -   40s
     0     0 1692030.24    0 2329          - 1692030.24      -     -   40s
     0     0 1692030.24    0 2332          - 1692030.24      -     -   40s
     0     0 1692030.24    0 2403          - 1692030.24      -     -   41s
     0     0 1692030.24    0 2383          - 1692030.24      -     -   41s
     0     0 1692030.24    0 2369          - 1692030.24      -     -   41s
     0     0 1692030.24    0 2392          - 1692030.24      -     -   41s
     0     0 1692030.24    0 2326          - 1692030.24      -     -   41s
     0     0 1692030.24    0 2342          - 1692030.24      -     -   42s
     0     0 1692030.24    0 2350          - 1692030.24      -     -   42s
     0     0 1692030.24    0 2287          - 1692030.24      -     -   43s
     0     0 1692030.24    0 2306          - 1692030.24      -     -   44s
     0     0 1692030.24    0 2320          - 1692030.24      -     -   44s
     0     0 1692030.24    0 2318          - 1692030.24      -     -   44s
     0     0 1691993.05    0 2237          - 1691993.05      -     -   45s
     0     0 1691985.22    0 2304          - 1691985.22      -     -   45s
     0     0 1691985.22    0 2285          - 1691985.22      -     -   46s
     0     2 1691985.22    0 2285          - 1691985.22      -     -   53s
     7    16 1691640.85    3 2108          - 1691640.85      -  2580   55s
    55   106 1690982.46    6 2183          - 1691008.14      -  3582   70s
   349   439 1690163.15   13 2054          - 1691008.14      -  1218   75s
  1077  1227 1689785.39   37 1653          - 1691008.14      -   483   80s
  2013  2177 1689785.39   78 1606          - 1691008.14      -   285   85s
  3165  3317 1689746.69  123 1546          - 1691008.14      -   198   90s
  4234  4469 1689746.69  161 1497          - 1691008.14      -   175   95s
  4859  5125 1689746.69  183 1461          - 1691008.14      -   166  100s
  5980  6074 1689746.68  218 1415          - 1691008.14      -   155  112s
  6297  6689 1689746.68  236 1391          - 1691008.14      -   155  115s
  7390  7795 1689746.68  270 1324          - 1691008.14      -   144  120s
  8682  9124 1689623.98  313 1282          - 1691008.14      -   134  127s
  9127  9585 1689623.98  314 1281          - 1691008.14      -   131  130s
 10604 11125 1689623.98  371 1237          - 1691008.14      -   125  137s
 11672 12245 1689623.98  402 1202          - 1691008.14      -   120  142s
 12261 12760 1688936.96  413 1244          - 1691008.14      -   118  145s
 12781 12762 1685539.60  389 3176          - 1691008.14      -   118  170s
 12784 12764 1685233.53   17 2691          - 1691008.14      -   118  175s
 12789 12768 1689623.98  381 2601          - 1691008.14      -   118  180s
 12795 12772 1685445.59  440 2502          - 1691008.14      -   118  197s
 12797 12776 1691008.14   13 2471          - 1691008.14      -   145  200s
 12827 12818 1691008.14   17 2428          - 1691008.14      -   152  206s
 12914 12894 1691008.14   20 2238          - 1691008.14      -   167  211s
 13024 12986 1690697.31   22 2149          - 1691008.14      -   175  215s
 13207 13088 1690044.88   26 2081          - 1691008.14      -   183  220s
 13381 13202 1690044.88   29 2074          - 1691008.14      -   191  233s
H13383 12563                    1569956.3107 1691008.14  7.71%   191  233s
H13420 11966                    1572117.8256 1691008.14  7.56%   192  243s
H13421 11389                    1572117.8256 1691008.14  7.56%   192  243s
H13423 10840                    1572849.2862 1691008.14  7.51%   192  243s
H13427  9355                    1572849.2862 1691008.14  7.51%   192  243s
H13433  8907                    1572849.2865 1691008.14  7.51%   192  243s
 13443  8991 1690044.88   30 2074 1572849.29 1691008.14  7.51%   192  245s
H13530  8562                    1573887.8399 1691008.14  7.44%   194  247s
H13531  8158                    1575126.7613 1691008.14  7.36%   194  247s
H13537  7065                    1580677.1538 1691008.14  6.98%   194  247s
H13539  6737                    1584235.2604 1691008.14  6.74%   194  247s
 13554  6481 1684273.04   31 2079 1584235.26 1691008.14  6.74%   195  258s
H13615  6187                    1590540.7395 1691008.14  6.32%   198  270s
H13630  5380                    1594458.7345 1691008.14  6.06%   198  270s
H13640  5248                    1594458.7345 1691008.14  6.06%   198  272s
H13750  5006                    1594944.6448 1691008.14  6.02%   200  274s
H13752  4582                    1596551.9949 1691008.14  5.92%   200  274s
H13753  4385                    1597120.0808 1691008.14  5.88%   200  274s
H13764  4018                    1597472.1122 1691008.14  5.86%   200  274s
 13774  3888 1689689.69   34 2017 1597472.11 1691008.14  5.86%   200  275s
H13775  3728                    1675082.9035 1691008.14  0.95%   200  275s
H13777  3576                    1675082.9041 1691008.14  0.95%   200  275s
H13796  3425                    1675082.9043 1691008.14  0.95%   201  275s
H13826  3173                    1689864.7432 1691008.14  0.07%   201  278s
 13962  3220 1688915.28   39 1950 1689864.74 1691008.14  0.07%   203  282s
 14185  3132 1688489.78   44 1880 1689864.74 1691008.14  0.07%   205  286s
 14440  2904     cutoff   19      1689864.74 1690962.27  0.06%   210  292s
 14515  2926 1689908.85   36 1720 1689864.74 1690872.08  0.06%   215  295s
 14866  2933     cutoff   54      1689864.74 1690872.08  0.06%   214  300s
 15301  2909 1689908.85   72 1645 1689864.74 1690399.71  0.03%   213  307s
 15584  2656 1689897.41   84 1564 1689864.74 1690399.71  0.03%   211  310s
 15716  2629 1689897.41   90 1546 1689864.74 1690399.71  0.03%   211  316s
 15995  2457 1689874.26  101 1485 1689864.74 1690399.71  0.03%   209  321s
 16106  2499     cutoff  106      1689864.74 1690295.19  0.03%   208  325s
 16652  2304 1689874.26  126 1424 1689864.74 1690295.19  0.03%   204  331s
 16798  2395 1689874.26  132 1404 1689864.74 1690268.86  0.02%   205  335s
 17431  2845 1689874.26  162 1324 1689864.74 1690268.86  0.02%   200  340s
 18834  2959 1689873.42  222 1114 1689864.74 1690268.86  0.02%   189  345s
 19710  3686 1689873.42  266 1068 1689864.74 1690268.86  0.02%   182  351s
 21239  4470     cutoff  335      1689864.74 1690268.86  0.02%   172  357s
 21854  6259 1689865.78  366  925 1689864.74 1690071.43  0.01%   169  369s
 23849  8028 1689869.44   77 1624 1689864.74 1690071.43  0.01%   159  378s
 26076  9193 1689869.43  140 1427 1689864.74 1690048.71  0.01%   150  386s
 27448 11959 1689869.43  179 1350 1689864.74 1689908.86  0.00%   145  397s
 30926 12146 1689869.43  340 1176 1689864.74 1689908.86  0.00%   132  409s
 31137 13739 1689869.43  348 1159 1689864.74 1689908.86  0.00%   132  415s
H31921 13739                    1689869.0450 1689908.86  0.00%   129  415s
H33081 10891                    1689869.0452 1689908.86  0.00%   125  428s
H33284 10891                    1689869.4358 1689908.86  0.00%   124  428s
 34194 11878 1689869.43  489  987 1689869.44 1689908.86  0.00%   123  434s
H34415 11068                    1689870.5102 1689908.86  0.00%   123  434s
 35457 10560 1689908.86   51 1781 1689870.51 1689908.86  0.00%   122  439s
 36495 11383 1689908.85   57 1701 1689870.51 1689908.86  0.00%   121  450s
H36731 11383                    1689908.8516 1689908.86  0.00%   121  450s
 37687 12394 1689908.85   64 1684 1689908.85 1689908.86  0.00%   123  457s
 38892 13362 1689908.85   73 1667 1689908.85 1689908.86  0.00%   121  464s
 40068  2172 1689908.85   81 1654 1689908.85 1689908.86  0.00%   121  470s

Cutting planes:
  Gomory: 34
  Cover: 433
  Implied bound: 1143
  MIR: 3561
  Flow cover: 7135
  Flow path: 734
  Network: 12
  RLT: 104
  Relax-and-lift: 803
  BQP: 5
  PSD: 66

Explored 40957 nodes (5322233 simplex iterations) in 470.75 seconds (381.80 work units)
Thread count was 32 (of 32 available processors)

Solution count 2: 1.68991e+06 1.68991e+06
No other solutions better than 1.68991e+06

Optimal solution found (tolerance 1.00e-05)
Best objective 1.689908851554e+06, best bound 1.689908857058e+06, gap 0.0000%

In [8]:
if model.status == GRB.OPTIMAL:
    num_solutions = model.SolCount
    print(f"\n--- Solution Pool Analysis ---")
    print(f"Found {num_solutions} solutions in the pool.")

    if num_solutions > 1:
        best_obj = model.objVal
        print(f"Best objective value: {best_obj:.8f}\n")

        for i in range(num_solutions):
            model.setParam(GRB.Param.SolutionNumber, i)
            pool_obj = model.PoolObjVal
            diff = best_obj - pool_obj
            
            print(f"Solution {i}: Objective = {pool_obj},  Difference from best = {diff}")

    model.setParam(GRB.Param.SolutionNumber, 0)
    
    x_hol = np.array([[x_hol[i, t].X for t in range(T)] for i in range(I)])
    yp_hol = np.array([[[yp_hol[i, t, s].X for s in range(S)] for t in range(T)] for i in range(I)]) ; ym_hol = np.array([[[ym_hol[i, t, s].X for s in range(S)] for t in range(T)] for i in range(I)])
    dp_hol = np.array([[[dp_hol[i, t, s].X for s in range(S)] for t in range(T)] for i in range(I)]) ; dm_hol = np.array([[[dm_hol[i, t, s].X for s in range(S)] for t in range(T)] for i in range(I)])
    zc_hol = np.array([[[zc_hol[i, t, s].X for s in range(S)] for t in range(T)] for i in range(I)]) ; zd_hol = np.array([[[zd_hol[i, t, s].X for s in range(S)] for t in range(T)] for i in range(I)])
    z_hol = np.array([[[z_hol[i, t, s].X for s in range(S)] for t in range(T+1)] for i in range(I)]) ; original_objval = model.objVal
    phi1_hol = np.array([[[phi1_hol[i, t, s].X for s in range(S)] for t in range(T)] for i in range(I)]) ; phi2_hol = np.array([[[phi2_hol[i, t, s].X for s in range(S)] for t in range(T)] for i in range(I)])
    phi3_hol = np.array([[[phi3_hol[i, t, s].X for s in range(S)] for t in range(T)] for i in range(I)]) ; phi4_hol = np.array([[[phi4_hol[i, t, s].X for s in range(S)] for t in range(T)] for i in range(I)])
    phi5_hol = np.array([[[phi5_hol[i, t, s].X for s in range(S)] for t in range(T)] for i in range(I)]) ; phi6_hol = np.array([[[phi6_hol[i, t, s].X for s in range(S)] for t in range(T)] for i in range(I)])
    phi7_hol = np.array([[[phi7_hol[i, t, s].X for s in range(S)] for t in range(T)] for i in range(I)]) ; OBJ_HOL = model.objVal
    
    zc0_hol = np.array([[zc0_hol[i, t].X for t in range(T)] for i in range(I)]) ; zcR_hol = np.array([[zcR_hol[i, t].X for t in range(T)] for i in range(I)])
    zd0_hol = np.array([[zd0_hol[i, t].X for t in range(T)] for i in range(I)]) ; zdR_hol = np.array([[zdR_hol[i, t].X for t in range(T)] for i in range(I)])

--- Solution Pool Analysis ---
Found 2 solutions in the pool.
Best objective value: 1689908.85155376

Solution 0: Objective = 1689908.8515537635,  Difference from best = 0.0
Solution 1: Objective = 1689908.8515645755,  Difference from best = -1.0811956599354744e-05

In [9]:
if model.status == GRB.OPTIMAL:        
    try:
        lambda_dual = {}
        for t, s in product(range(T), range(S)): 
            lambda_dual[t, s] = balance_constraints[t, s].Pi
        print("Direct dual extraction successful!")
        
    except AttributeError:
        print("\nDirect dual extraction failed. Using Model.fixed() method...")
        
        fixed_model = model.fixed()
        
        fixed_x_hol = {(i, t): fixed_model.getVarByName(f"x[{i},{t}]") for i, t in product(range(I), range(T))}
        fixed_yp_hol = {(i, t, s): fixed_model.getVarByName(f"yp[{i},{t},{s}]") for i, t, s in product(range(I), range(T), range(S))}
        fixed_ym_hol = {(i, t, s): fixed_model.getVarByName(f"ym[{i},{t},{s}]") for i, t, s in product(range(I), range(T), range(S))}

        linear_obj_for_fixed_model = (
            gp.quicksum(P_DA[t] * fixed_x_hol[i, t] for i, t in product(range(I), range(T))) +
            gp.quicksum((1/S) * (P_RT[t, s] * fixed_yp_hol[i, t, s] - P_PN[t, s] * fixed_ym_hol[i, t, s]) 
                         for i, t, s in product(range(I), range(T), range(S)))
        )
        
        reg_fixed = gp.quicksum(fixed_x_hol[i, t] * fixed_x_hol[i, t] for i, t in product(range(I), range(T)))
        regularized_obj_fixed = linear_obj_for_fixed_model - epsilon * reg_fixed
        # regularized_obj_fixed = linear_obj_for_fixed_model
        
        fixed_model.setParam("Method", 1)
        fixed_model.setParam("MIPGap", 1e-5)
        fixed_model.setParam(GRB.Param.PoolSearchMode, 2)
        fixed_model.setParam(GRB.Param.PoolSolutions, 2)
        fixed_model.setObjective(regularized_obj_fixed, GRB.MAXIMIZE)
        fixed_model.optimize()
        
        if fixed_model.status == GRB.OPTIMAL:
            original_obj_val = (
                sum(P_DA[t] * x_hol[i, t] for i, t in product(range(I), range(T))) +
                sum((1/S) * (P_RT[t, s] * yp_hol[i, t, s] - P_PN[t, s] * ym_hol[i, t, s]) 
                    for i, t, s in product(range(I), range(T), range(S)))
                - epsilon * sum(x_hol[i, t] * x_hol[i, t] for i, t in product(range(I), range(T)))
            )
            
            fixed_obj = fixed_model.objVal
            obj_diff = abs(original_obj_val - fixed_obj)

            print(f"Original Objective: {original_obj_val:.6f}")
            print(f"Fixed Model Objective: {fixed_obj:.6f}")
            print(f"Difference: {obj_diff:.10f}")
            
            if obj_diff < 1e-6:
                print("✅ Objective values match! Fixed model is consistent.")
            else:
                print("⚠️ Warning: Objective values don't match.")

            num_solutions = fixed_model.SolCount
            print(f"\n--- Fixed Model Solution Pool Analysis ---")
            print(f"Found {num_solutions} solutions in the pool.")

            if num_solutions > 1:
                best_obj = fixed_model.objVal
                print(f"Best objective value: {best_obj:.8f}\n")
                for i in range(num_solutions):
                    fixed_model.setParam(GRB.Param.SolutionNumber, i)
                    pool_obj = fixed_model.PoolObjVal
                    diff = abs(best_obj - pool_obj)
                    print(f"Solution {i}: Objective = {pool_obj:.8f},  Difference = {diff:.8f}")
                fixed_model.setParam(GRB.Param.SolutionNumber, 0)

            print("\n=== Solution Comparison ===")
            fixed_vars = {var.VarName: var.X for var in fixed_model.getVars()}
            
            print("=== x values by individual ===")
            print("Individual | Time | Original x | Fixed x | Difference")
            print("-" * 55)
            
            max_x_diff = 0
            for i in range(I):
                for t in range(T):
                    original_x = x_hol[i, t]
                    fixed_x = fixed_vars.get(f"x[{i},{t}]", 0)
                    diff = abs(original_x - fixed_x)
                    max_x_diff = max(max_x_diff, diff)
                    if original_x != 0:
                        print(f"{i:10d} | {t:4d} | {original_x:10.6f} | {fixed_x:7.6f} | {diff:10.8f}")
            
            print("\n=== yp values sum over i (scenario average) ===")
            print("Time | Original yp_sum | Fixed yp_sum | Difference")
            print("-" * 52)
            max_yp_diff = 0
            for t in range(14,16):
                original_yp_sum = sum(sum(yp_hol[i, t, s] for i in range(I)) for s in range(S)) / S
                fixed_yp_sum = sum(sum(fixed_vars.get(f"yp[{i},{t},{s}]", 0) for i in range(I)) for s in range(S)) / S
                diff = abs(original_yp_sum - fixed_yp_sum)
                max_yp_diff = max(max_yp_diff, diff)
                print(f"{t:4d} | {original_yp_sum:14.6f} | {fixed_yp_sum:12.6f} | {diff:10.8f}")

        lambda_dual = np.zeros((T, S))
        if fixed_model.status == GRB.OPTIMAL:
            for t, s in product(range(T), range(S)):
                constr_name = f"balance_{t}_{s}"
                try:
                    constr = fixed_model.getConstrByName(constr_name)
                    if constr is not None:
                        lambda_dual[t, s] = constr.Pi
                    else:
                        lambda_dual[t, s] = np.nan
                except:
                    lambda_dual[t, s] = np.nan 
                    
            print("\nModel.fixed() dual extraction successful!")
        else:
            print("Fixed model optimization failed. Setting dual to zeros.")
            lambda_dual = np.zeros((T, S))

        print("\nInternal Settlement Prices (Dual Variables):")
        for t, s in product(range(T), range(1,2)):
            print(f"λ_{t}(ξ_{s}) = {lambda_dual[t, s]:.4f}")
            
else:
    print("No optimal solution found.")
    lambda_dual = {(t, s): np.nan for t in range(T) for s in range(S)}
    x_hol = yp_hol = ym_hol = dp_hol = dm_hol = z_hol = zc_hol = zd_hol = None
    original_objval = None

Direct dual extraction failed. Using Model.fixed() method...
Set parameter Method to value 1
Set parameter MIPGap to value 1e-05
Set parameter PoolSearchMode to value 2
Set parameter PoolSolutions to value 2
Gurobi Optimizer version 12.0.2 build v12.0.2rc0 (win64 - Windows 11.0 (26100.2))

CPU model: 13th Gen Intel(R) Core(TM) i9-13900K, instruction set [SSE2|AVX|AVX2]
Thread count: 24 physical cores, 32 logical processors, using up to 32 threads

Non-default parameters:
MIPGap  1e-05
Method  1
PoolSolutions  2
PoolSearchMode  2

Optimize a model with 53380 rows, 34540 columns and 134500 nonzeros
Model fingerprint: 0x6f4a0359
Model has 120 quadratic objective terms
Coefficient statistics:
  Matrix range     [5e-03, 8e+02]
  Objective range  [2e+00, 2e+02]
  QObjective range [2e-07, 2e-07]
  Bounds range     [1e-06, 1e+00]
  RHS range        [8e-02, 8e+02]
Presolve time: 0.03s
Presolved: 3138 rows, 2368 columns, 11394 nonzeros
Presolved model has 91 quadratic objective terms

Iteration    Objective       Primal Inf.    Dual Inf.      Time
       0    1.9103406e+06   0.000000e+00   4.335415e+06      0s
Extra simplex iterations after uncrush: 771
    6858    1.6899089e+06   0.000000e+00   0.000000e+00      0s

Solved in 6858 iterations and 0.13 seconds (0.11 work units)
Optimal objective  1.689908852e+06
Original Objective: 1689908.851554
Fixed Model Objective: 1689908.851509
Difference: 0.0000446853
⚠️ Warning: Objective values don't match.

--- Fixed Model Solution Pool Analysis ---
Found 1 solutions in the pool.

=== Solution Comparison ===
=== x values by individual ===
Individual | Time | Original x | Fixed x | Difference
-------------------------------------------------------
         0 |    7 |   4.889341 | 4.889341 | 0.00000000
         0 |    9 | 113.963492 | 113.963492 | 0.00000037
         0 |   10 | 220.981621 | 220.981622 | 0.00000046
         0 |   11 | 244.210536 | 244.210536 | 0.00000009
         0 |   16 |  99.049276 | 99.049276 | 0.00000001
         0 |   18 |  57.282487 | 57.282487 | 0.00000001
         0 |   19 |  54.432453 | 54.432453 | 0.00000001
         0 |   20 |  13.582803 | 13.582803 | 0.00000000
         0 |   21 |   4.433663 | 5.533269 | 1.09960554
         1 |   16 |  99.049276 | 99.049276 | 0.00000005
         1 |   18 |  53.316970 | 53.316970 | 0.00000000
         1 |   19 |  64.595962 | 64.595962 | 0.00000000
         1 |   20 |  18.829372 | 18.829372 | 0.00000000
         1 |   21 |   4.433663 | 3.883860 | 0.54980278
         2 |   11 |  10.994149 | 10.994149 | 0.00000037
         2 |   14 | 910.233105 | 910.233105 | 0.00000000
         2 |   16 | 142.661773 | 142.661773 | 0.00000000
         2 |   18 |  57.282488 | 57.282488 | 0.00000002
         2 |   19 |  54.432453 | 54.432453 | 0.00000001
         2 |   20 |  17.023223 | 17.023223 | 0.00000002
         2 |   21 |   0.718779 | 0.718779 | 0.00000000
         3 |    4 |   0.169352 | 0.169352 | 0.00000000
         3 |    6 |   0.483258 | 0.483258 | 0.00000000
         3 |   14 |   4.358990 | 4.358990 | 0.00000000
         3 |   16 |  99.049276 | 99.049276 | 0.00000003
         3 |   18 |  59.759001 | 59.759001 | 0.00000000
         3 |   19 |  50.152148 | 50.152148 | 0.00000000
         3 |   20 |  17.023223 | 17.023223 | 0.00000002
         3 |   21 |   3.430744 | 3.430744 | 0.00000000
         4 |    6 |   0.570458 | 0.570458 | 0.00000000
         4 |    8 |  18.418341 | 18.418342 | 0.00000094
         4 |   16 |  99.049276 | 99.049276 | 0.00000002
         4 |   18 |  68.790925 | 68.790925 | 0.00000001
         4 |   19 |  57.016553 | 57.016553 | 0.00000000
         4 |   20 |  18.000637 | 18.000637 | 0.00000000
         4 |   21 |   4.433663 | 3.883860 | 0.54980276

=== yp values sum over i (scenario average) ===
Time | Original yp_sum | Fixed yp_sum | Difference
----------------------------------------------------
  14 |     179.828159 |   179.828159 | 0.00000000
  15 |    1213.424953 |  1213.424953 | 0.00000006

Model.fixed() dual extraction successful!

Internal Settlement Prices (Dual Variables):
λ_0(ξ_1) = 0.0000
λ_1(ξ_1) = 0.0000
λ_2(ξ_1) = 0.0000
λ_3(ξ_1) = 0.0000
λ_4(ξ_1) = -3.9812
λ_5(ξ_1) = 0.0000
λ_6(ξ_1) = -9.3548
λ_7(ξ_1) = -3.6911
λ_8(ξ_1) = -5.7535
λ_9(ξ_1) = -3.6372
λ_10(ξ_1) = -13.6682
λ_11(ξ_1) = -7.1255
λ_12(ξ_1) = 0.0000
λ_13(ξ_1) = 0.0000
λ_14(ξ_1) = -17.0142
λ_15(ξ_1) = 0.0000
λ_16(ξ_1) = -8.5761
λ_17(ξ_1) = 0.0000
λ_18(ξ_1) = -8.6372
λ_19(ξ_1) = -13.9846
λ_20(ξ_1) = -6.1535
λ_21(ξ_1) = -5.6083
λ_22(ξ_1) = -0.5687
λ_23(ξ_1) = 0.0000

In [10]:
for i, t, s in product(range(I), range(T), range(S)):
    if yp_hol[i, t, s] != 0 and ym_hol[i, t, s] != 0: print("[VIOLATION] YP-YM", i, t, s, yp_hol[i,t,s], ym_hol[i,t,s])
    if dp_hol[i, t, s] != 0 and dm_hol[i, t, s] != 0: print("[VIOLATION] DP-DM", i, t, s, dp_hol[i,t,s], dm_hol[i,t,s])
    if dp_hol[i, t, s] != 0 and ym_hol[i, t, s] != 0: print("[VIOLATION] DP-YM", i, t, s, dp_hol[i,t,s], ym_hol[i,t,s])
    if yp_hol[i, t, s] != 0 and dm_hol[i, t, s] != 0: print("[VIOLATION] YP-DM", i, t, s, yp_hol[i,t,s], dm_hol[i,t,s])
    if ym_hol[i, t, s] != 0 and zc_hol[i, t, s] != 0: print("[VIOLATION] YM-ZC", i, t, s, ym_hol[i,t,s], zc_hol[i,t,s])
    if dm_hol[i, t, s] != 0 and zc_hol[i, t, s] != 0: print("[VIOLATION] DM-ZC", i, t, s, dm_hol[i,t,s], zc_hol[i,t,s])
    if zc_hol[i, t, s] != 0 and zd_hol[i, t, s] != 0: print("[VIOLATION] ZC-ZD", i, t, s, zc_hol[i,t,s], zd_hol[i,t,s])

In [11]:
print("\n=== 모든 LDR 계수 (i, t별) ===")
print("Individual | Time | Variable | 상수항     | R계수    ")
print("-" * 50)

for t in range(7,20):
    for i in range(I):
        print(f"{i:10d} | {t:4d} | zc       | {zc0_hol[i,t]:8.4f} | {zcR_hol[i,t]:7.4f}")
        print(f"{i:10d} | {t:4d} | zd       | {zd0_hol[i,t]:8.4f} | {zdR_hol[i,t]:7.4f}")
        print(f"{i:10d} | {t:4d} | x (1st)  | {x_hol[i,t]:8.4f} |    -    ")
        print("-" * 50)

=== 모든 LDR 계수 (i, t별) ===
Individual | Time | Variable | 상수항     | R계수
--------------------------------------------------
         0 |    7 | zc       |   0.0000 |  0.0000
         0 |    7 | zd       |   0.0000 |  0.0000
         0 |    7 | x (1st)  |   4.8893 |    -
--------------------------------------------------
         1 |    7 | zc       |   1.1641 |  0.0000
         1 |    7 | zd       |   0.0000 |  0.0000
         1 |    7 | x (1st)  |   0.0000 |    -
--------------------------------------------------
         2 |    7 | zc       |   1.4627 |  0.0000
         2 |    7 | zd       |   0.0000 |  0.0000
         2 |    7 | x (1st)  |   0.0000 |    -
--------------------------------------------------
         3 |    7 | zc       |   0.0818 |  0.0000
         3 |    7 | zd       |   0.0000 |  0.0000
         3 |    7 | x (1st)  |   0.0000 |    -
--------------------------------------------------
         4 |    7 | zc       |   0.9202 |  0.0000
         4 |    7 | zd       |   0.0000 |  0.0000
         4 |    7 | x (1st)  |   0.0000 |    -
--------------------------------------------------
         0 |    8 | zc       |   3.9928 |  0.0000
         0 |    8 | zd       |   0.0000 |  0.0000
         0 |    8 | x (1st)  |   0.0000 |    -
--------------------------------------------------
         1 |    8 | zc       |   1.5087 |  0.0000
         1 |    8 | zd       |   0.0000 |  0.0000
         1 |    8 | x (1st)  |   0.0000 |    -
--------------------------------------------------
         2 |    8 | zc       |   4.6662 |  0.0000
         2 |    8 | zd       |   0.0000 |  0.0000
         2 |    8 | x (1st)  |   0.0000 |    -
--------------------------------------------------
         3 |    8 | zc       |   1.0016 |  0.0000
         3 |    8 | zd       |   0.0000 |  0.0000
         3 |    8 | x (1st)  |   0.0000 |    -
--------------------------------------------------
         4 |    8 | zc       |   0.0000 |  0.0000
         4 |    8 | zd       |   0.0000 |  0.0000
         4 |    8 | x (1st)  |  18.4183 |    -
--------------------------------------------------
         0 |    9 | zc       |   0.0000 |  0.0000
         0 |    9 | zd       |   0.0000 |  0.0000
         0 |    9 | x (1st)  | 113.9635 |    -
--------------------------------------------------
         1 |    9 | zc       |  18.0606 |  0.0000
         1 |    9 | zd       |   0.0000 |  0.0000
         1 |    9 | x (1st)  |   0.0000 |    -
--------------------------------------------------
         2 |    9 | zc       |  18.6331 |  0.0000
         2 |    9 | zd       |   0.0000 |  0.0000
         2 |    9 | x (1st)  |   0.0000 |    -
--------------------------------------------------
         3 |    9 | zc       |   5.5543 |  0.0000
         3 |    9 | zd       |   0.0000 |  0.0000
         3 |    9 | x (1st)  |   0.0000 |    -
--------------------------------------------------
         4 |    9 | zc       |   6.0872 |  0.0000
         4 |    9 | zd       |   0.0000 |  0.0000
         4 |    9 | x (1st)  |   0.0000 |    -
--------------------------------------------------
         0 |   10 | zc       |   0.0000 |  0.0000
         0 |   10 | zd       |   0.0000 |  0.0000
         0 |   10 | x (1st)  | 220.9816 |    -
--------------------------------------------------
         1 |   10 | zc       |  40.6763 |  0.0000
         1 |   10 | zd       |   0.0000 |  0.0000
         1 |   10 | x (1st)  |   0.0000 |    -
--------------------------------------------------
         2 |   10 | zc       |  37.9442 |  0.0000
         2 |   10 | zd       |   0.0000 |  0.0000
         2 |   10 | x (1st)  |   0.0000 |    -
--------------------------------------------------
         3 |   10 | zc       |  17.7276 |  0.0000
         3 |   10 | zd       |   0.0000 |  0.0000
         3 |   10 | x (1st)  |   0.0000 |    -
--------------------------------------------------
         4 |   10 | zc       |  12.2746 |  0.0000
         4 |   10 | zd       |   0.0000 |  0.0000
         4 |   10 | x (1st)  |   0.0000 |    -
--------------------------------------------------
         0 |   11 | zc       |   0.0000 |  0.0000
         0 |   11 | zd       |   0.0000 |  0.0000
         0 |   11 | x (1st)  | 244.2105 |    -
--------------------------------------------------
         1 |   11 | zc       |  43.8522 |  0.0000
         1 |   11 | zd       |   0.0000 |  0.0000
         1 |   11 | x (1st)  |   0.0000 |    -
--------------------------------------------------
         2 |   11 | zc       |  42.6871 |  0.0000
         2 |   11 | zd       |   0.0000 |  0.0000
         2 |   11 | x (1st)  |  10.9941 |    -
--------------------------------------------------
         3 |   11 | zc       |  40.1131 |  0.0000
         3 |   11 | zd       |   0.0000 |  0.0000
         3 |   11 | x (1st)  |   0.0000 |    -
--------------------------------------------------
         4 |   11 | zc       |  29.0621 |  0.0000
         4 |   11 | zd       |   0.0000 |  0.0000
         4 |   11 | x (1st)  |   0.0000 |    -
--------------------------------------------------
         0 |   12 | zc       |  31.7994 |  0.0000
         0 |   12 | zd       |   0.0000 |  0.0000
         0 |   12 | x (1st)  |   0.0000 |    -
--------------------------------------------------
         1 |   12 | zc       |   5.1459 |  0.0000
         1 |   12 | zd       |   0.0000 |  0.0000
         1 |   12 | x (1st)  |   0.0000 |    -
--------------------------------------------------
         2 |   12 | zc       |   4.2687 |  0.0000
         2 |   12 | zd       |   0.0000 |  0.0000
         2 |   12 | x (1st)  |   0.0000 |    -
--------------------------------------------------
         3 |   12 | zc       |  41.9695 |  0.0000
         3 |   12 | zd       |   0.0000 |  0.0000
         3 |   12 | x (1st)  |   0.0000 |    -
--------------------------------------------------
         4 |   12 | zc       |  25.1476 |  0.0000
         4 |   12 | zd       |   0.0000 |  0.0000
         4 |   12 | x (1st)  |   0.0000 |    -
--------------------------------------------------
         0 |   13 | zc       |   0.0000 |  0.0000
         0 |   13 | zd       |   0.0000 |  0.0000
         0 |   13 | x (1st)  |   0.0000 |    -
--------------------------------------------------
         1 |   13 | zc       |   0.0000 |  0.0000
         1 |   13 | zd       |  63.1147 |  0.0000
         1 |   13 | x (1st)  |   0.0000 |    -
--------------------------------------------------
         2 |   13 | zc       |   0.0000 |  0.0000
         2 |   13 | zd       |   0.0000 |  0.0000
         2 |   13 | x (1st)  |   0.0000 |    -
--------------------------------------------------
         3 |   13 | zc       |   0.0000 |  0.0000
         3 |   13 | zd       |  86.2227 |  0.0000
         3 |   13 | x (1st)  |   0.0000 |    -
--------------------------------------------------
         4 |   13 | zc       |   0.0000 |  0.0000
         4 |   13 | zd       |   9.2726 |  0.0000
         4 |   13 | x (1st)  |   0.0000 |    -
--------------------------------------------------
         0 |   14 | zc       |  49.5113 |  0.0000
         0 |   14 | zd       |   0.0000 |  0.0000
         0 |   14 | x (1st)  |   0.0000 |    -
--------------------------------------------------
         1 |   14 | zc       |  70.6421 |  0.0000
         1 |   14 | zd       |   0.0000 |  0.0000
         1 |   14 | x (1st)  |   0.0000 |    -
--------------------------------------------------
         2 |   14 | zc       |   0.0000 |  0.0000
         2 |   14 | zd       |   0.0000 |  0.0000
         2 |   14 | x (1st)  | 910.2331 |    -
--------------------------------------------------
         3 |   14 | zc       | 100.0000 |  0.0000
         3 |   14 | zd       |   0.0000 |  0.0000
         3 |   14 | x (1st)  |   4.3590 |    -
--------------------------------------------------
         4 |   14 | zc       |  44.1604 |  0.0000
         4 |   14 | zd       |   0.0000 |  0.0000
         4 |   14 | x (1st)  |   0.0000 |    -
--------------------------------------------------
         0 |   15 | zc       |   0.0000 |  0.0000
         0 |   15 | zd       |  69.0958 |  0.0000
         0 |   15 | x (1st)  |   0.0000 |    -
--------------------------------------------------
         1 |   15 | zc       |   0.0000 |  0.0000
         1 |   15 | zd       |  83.6422 |  0.0000
         1 |   15 | x (1st)  |   0.0000 |    -
--------------------------------------------------
         2 |   15 | zc       |   0.0000 |  0.0000
         2 |   15 | zd       |  89.6158 |  0.0000
         2 |   15 | x (1st)  |   0.0000 |    -
--------------------------------------------------
         3 |   15 | zc       |   0.0000 |  0.0000
         3 |   15 | zd       |  81.0000 |  0.0000
         3 |   15 | x (1st)  |   0.0000 |    -
--------------------------------------------------
         4 |   15 | zc       |   0.0000 |  0.0000
         4 |   15 | zd       |  86.0256 |  0.0000
         4 |   15 | x (1st)  |   0.0000 |    -
--------------------------------------------------
         0 |   16 | zc       |   0.0000 |  0.0000
         0 |   16 | zd       |   0.0000 |  0.0000
         0 |   16 | x (1st)  |  99.0493 |    -
--------------------------------------------------
         1 |   16 | zc       |   0.0000 |  0.0000
         1 |   16 | zd       |   0.0000 |  0.0000
         1 |   16 | x (1st)  |  99.0493 |    -
--------------------------------------------------
         2 |   16 | zc       |   0.0000 |  0.0000
         2 |   16 | zd       |   0.0000 |  0.0000
         2 |   16 | x (1st)  | 142.6618 |    -
--------------------------------------------------
         3 |   16 | zc       |   0.0000 |  0.0000
         3 |   16 | zd       |   0.0000 |  0.0000
         3 |   16 | x (1st)  |  99.0493 |    -
--------------------------------------------------
         4 |   16 | zc       |   0.0000 |  0.0000
         4 |   16 | zd       |   0.0000 |  0.0000
         4 |   16 | x (1st)  |  99.0493 |    -
--------------------------------------------------
         0 |   17 | zc       |   0.0000 |  0.0000
         0 |   17 | zd       |   0.0000 |  0.0000
         0 |   17 | x (1st)  |   0.0000 |    -
--------------------------------------------------
         1 |   17 | zc       |   0.0000 |  0.0000
         1 |   17 | zd       |   0.0000 |  0.0000
         1 |   17 | x (1st)  |   0.0000 |    -
--------------------------------------------------
         2 |   17 | zc       |   0.0000 |  0.0000
         2 |   17 | zd       |   0.0000 |  0.0000
         2 |   17 | x (1st)  |   0.0000 |    -
--------------------------------------------------
         3 |   17 | zc       |   0.0000 |  0.0000
         3 |   17 | zd       |   0.0000 |  0.0000
         3 |   17 | x (1st)  |   0.0000 |    -
--------------------------------------------------
         4 |   17 | zc       |   0.0000 |  0.0000
         4 |   17 | zd       |   0.0000 |  0.0000
         4 |   17 | x (1st)  |   0.0000 |    -
--------------------------------------------------
         0 |   18 | zc       |   0.0000 |  0.0000
         0 |   18 | zd       |   0.0000 |  0.0000
         0 |   18 | x (1st)  |  57.2825 |    -
--------------------------------------------------
         1 |   18 | zc       |   0.0000 |  0.0000
         1 |   18 | zd       |   0.0000 |  0.0000
         1 |   18 | x (1st)  |  53.3170 |    -
--------------------------------------------------
         2 |   18 | zc       |   0.0000 |  0.0000
         2 |   18 | zd       |   0.0000 |  0.0000
         2 |   18 | x (1st)  |  57.2825 |    -
--------------------------------------------------
         3 |   18 | zc       |   0.0000 |  0.0000
         3 |   18 | zd       |   0.0000 |  0.0000
         3 |   18 | x (1st)  |  59.7590 |    -
--------------------------------------------------
         4 |   18 | zc       |   0.0000 |  0.0000
         4 |   18 | zd       |   0.0000 |  0.0000
         4 |   18 | x (1st)  |  68.7909 |    -
--------------------------------------------------
         0 |   19 | zc       |   0.0000 |  0.0000
         0 |   19 | zd       |   0.0000 |  0.0000
         0 |   19 | x (1st)  |  54.4325 |    -
--------------------------------------------------
         1 |   19 | zc       |   0.0000 |  0.0000
         1 |   19 | zd       |   0.0000 |  0.0000
         1 |   19 | x (1st)  |  64.5960 |    -
--------------------------------------------------
         2 |   19 | zc       |   0.0000 |  0.0000
         2 |   19 | zd       |   0.0000 |  0.0000
         2 |   19 | x (1st)  |  54.4325 |    -
--------------------------------------------------
         3 |   19 | zc       |   0.0000 |  0.0000
         3 |   19 | zd       |   0.0000 |  0.0000
         3 |   19 | x (1st)  |  50.1521 |    -
--------------------------------------------------
         4 |   19 | zc       |   0.0000 |  0.0000
         4 |   19 | zd       |   0.0000 |  0.0000
         4 |   19 | x (1st)  |  57.0166 |    -
--------------------------------------------------

In [12]:
header = (f"{'t':>2} | {'R':>8} {'x':>8} {'y+':>8} {'y-':>8} {'d+':>8} {'d-':>8} {'zc':>8} {'zd':>8} {'z':>8}\n" + "-" * 90)
print("\n[HOLISTIC]") ; print(header)
for t in range(7, 22):
    R_avg = np.mean([R[:, t, s].sum() for s in range(S)]) ; x_sum = x_hol[:, t].sum()
    yp_avg = np.mean([yp_hol[:, t, s].sum() for s in range(S)]) ; ym_avg = np.mean([ym_hol[:, t, s].sum() for s in range(S)])
    dp_avg = np.mean([dp_hol[:, t, s].sum() for s in range(S)]) ; dm_avg = np.mean([dm_hol[:, t, s].sum() for s in range(S)])
    zc_avg = np.mean([zc_hol[:, t, s].sum() for s in range(S)]) ; zd_avg = np.mean([zd_hol[:, t, s].sum() for s in range(S)]) ; z_avg = np.mean([z_hol[:, t, s].sum() for s in range(S)])
    print(f"{t:>2} | {R_avg:>8.2f} {x_sum:>8.2f} {yp_avg:>8.2f} {ym_avg:>8.2f} {dp_avg:>8.2f} {dm_avg:>8.2f} {zc_avg:>8.2f} {zd_avg:>8.2f} {z_avg:>8.2f}")

[HOLISTIC]
 t |        R        x       y+       y-       d+       d-       zc       zd        z
------------------------------------------------------------------------------------------
 7 |    12.59     4.89     4.30     0.23     4.66     4.66     3.63     0.00     1.00
 8 |    41.70    18.42    12.62     0.51    16.10    16.10    11.17     0.00     4.26
 9 |   185.31   113.96    29.72     6.70   103.39   103.39    48.34     0.00    14.31
10 |   445.25   220.98   117.68     2.04   185.45   185.45   108.62     0.00    57.82
11 |   652.06   255.20   241.14     0.00   183.50   183.50   155.71     0.00   155.58
12 |   860.69     0.00   752.36     0.00     0.00     0.00   108.33     0.00   295.72
13 |  1397.66     0.00  1556.27     0.00     0.00     0.00     0.00   158.61   393.22
14 |  1338.06   914.59   179.83    20.67   508.43   508.43   264.31     0.00   216.98
15 |   804.05     0.00  1213.42     0.00     0.00     0.00     0.00   409.38   454.87
16 |   756.56   538.86   223.64     5.94   160.45   160.45     0.00     0.00     0.00
17 |   738.45     0.00   738.45     0.00     0.00     0.00     0.00     0.00     0.00
18 |   493.98   296.43   197.55     0.00    62.36    62.36     0.00     0.00     0.00
19 |   399.71   280.63   125.65     6.57    52.20    52.20     0.00     0.00     0.00
20 |   112.98    84.46    30.90     2.38    26.42    26.42     0.00     0.00     0.00
21 |    20.80    17.45     4.34     0.99     8.85     8.85     0.00     0.00     0.00

In [13]:
data = []
for t, s in product(range(T), range(1,4)):
    data.append({
        'Time': t,
        'Scenario': s,
        'P_DA': round(P_DA[t], 2),
        'P_RT': round(P_RT[t, s], 2),
        'Dual': round(-lambda_dual[t, s] * S, 2),
        'P_PN': round(P_PN[t, s], 2)
    })
pd.DataFrame(data)

    Time  Scenario    P_DA    P_RT    Dual    P_PN
0      0         1 106.720  84.830  -0.000 213.440
1      0         2 106.720  74.950  -0.000 213.440
2      0         3 106.720  68.930  -0.000 213.440
3      1         1  93.130  67.580  -0.000 186.260
4      1         2  93.130  77.240  -0.000 186.260
5      1         3  93.130  81.930  -0.000 186.260
6      2         1  86.030  75.110  -0.000 172.060
7      2         2  86.030  50.800  -0.000 172.060
8      2         3  86.030  96.960  -0.000 193.920
9      3         1  82.960  57.710  -0.000 165.930
10     3         2  82.960  84.510  -0.000 169.020
11     3         3  82.960  61.810  -0.000 165.930
12     4         1  82.730  79.620  79.620 165.450
13     4         2  82.730  64.620  64.620 165.450
14     4         3  82.730  50.900  50.900 165.450
15     5         1  85.950  94.350  -0.000 188.700
16     5         2  85.950  74.940  -0.000 171.890
17     5         3  85.950  86.650  -0.000 173.290
18     6         1  93.550  91.210 187.100 187.100
19     6         2  93.550  62.310  62.310 187.100
20     6         3  93.550  51.920  51.920 187.100
21     7         1 102.330  73.820  73.820 204.650
22     7         2 102.330  89.170  89.170 204.650
23     7         3 102.330  76.890  76.890 204.650
24     8         1 122.120 115.070 115.070 244.240
25     8         2 122.120 115.160 115.160 244.240
26     8         3 122.120 107.950 107.950 244.240
27     9         1 132.150  72.740  72.740 264.290
28     9         2 132.150 129.370 129.370 264.290
29     9         3 132.150 126.070 126.070 264.290
30    10         1 136.680  81.700 273.360 273.360
31    10         2 136.680  87.950  87.950 273.360
32    10         3 136.680 147.390 147.390 294.790
33    11         1 142.310 142.510 142.510 285.020
34    11         2 142.310  97.320  97.320 284.620
35    11         3 142.310 123.410 123.410 284.620
36    12         1 157.020 232.470  -0.000 464.940
37    12         2 157.020 227.640  -0.000 455.290
38    12         3 157.020 160.380  -0.000 320.760
39    13         1 155.480 350.200  -0.000 700.390
40    13         2 155.480 195.060  -0.000 390.110
41    13         3 155.480 264.100  -0.000 528.190
42    14         1 170.140 110.070 340.280 340.280
43    14         2 170.140 113.340 113.340 340.280
44    14         3 170.140  88.870  88.870 340.280
45    15         1 183.990 311.250  -0.000 622.490
46    15         2 183.990 313.230  -0.000 626.450
47    15         3 183.990 333.860  -0.000 667.720
48    16         1 191.700 171.520 171.520 383.400
49    16         2 191.700 165.840 165.840 383.400
50    16         3 191.700 126.150 126.150 383.400
51    17         1 185.290 200.400  -0.000 400.800
52    17         2 185.290 157.480  -0.000 370.580
53    17         3 185.290 194.740  -0.000 389.480
54    18         1 155.510 172.740 172.740 345.490
55    18         2 155.510 152.410 152.410 311.020
56    18         3 155.510 162.010 162.010 324.020
57    19         1 139.850 117.610 279.690 279.690
58    19         2 139.850 112.700 112.700 279.690
59    19         3 139.850 130.680 130.680 279.690
60    20         1 136.050 123.070 123.070 272.100
61    20         2 136.050  96.370  96.370 272.100
62    20         3 136.050 117.960 117.960 272.100
63    21         1 133.000 112.170 112.170 266.000
64    21         2 133.000  66.570 266.000 266.000
65    21         3 133.000  92.900  92.900 266.000
66    22         1 127.880 122.130  11.370 255.750
67    22         2 127.880  83.080  -0.000 255.750
68    22         3 127.880  82.850  -0.000 255.750
69    23         1 121.230  81.240  -0.000 242.450
70    23         2 121.230  86.230  -0.000 242.450
71    23         3 121.230  77.850  -0.000 242.450

In [33]:
lambda_rep = np.zeros((T, S))

data = []
for t in range(T):
    for s in range(S):
        lambda_rep[t, s] = lambda_dual[t, s]
    p_rt_avg = np.mean(P_RT[t, :]) ; p_pn_avg = np.mean(P_PN[t, :])
    
    # lambda_rep[t, :] = np.mean(lambda_rep[t, :])
    lambda_rep[t, :] = np.mean(lambda_rep[t, :][lambda_rep[t, :] < 0]) if np.any(lambda_rep[t, :] < 0) else 0
    # lambda_rep[t, :] = np.mean(lambda_rep[t, :][np.abs(lambda_rep[t, :]) > 0]) if np.any(np.abs(lambda_rep[t, :]) > 0) else 0
    
    data.append({
        'Time': t, 'P_RT_avg': round(p_rt_avg, 2), 'Lambda': round(-lambda_rep[t, 0] * S, 2), 'P_PN_avg': round(p_pn_avg, 2)
    })
pd.DataFrame(data)

    Time  P_RT_avg   Lambda  P_PN_avg
0      0    62.570 2134.440   213.440
1      1    87.530 1862.560   196.750
2      2    74.840 1720.600   178.380
3      3    66.830 1659.280   167.120
4      4    72.650   78.370   168.650
5      5    86.840 1718.920   188.890
6      6    71.170   93.550   187.240
7      7    86.800  102.330   209.710
8      8   100.300  122.120   246.570
9      9   106.080  132.150   264.290
10    10   111.090  136.680   275.110
11    11   133.620  142.310   297.620
12    12   190.050   -0.000   390.240
13    13   290.800   -0.000   581.600
14    14   114.560  149.250   340.280
15    15   298.110   -0.000   596.220
16    16   144.900  191.700   383.890
17    17   199.120   12.650   417.680
18    18   150.100  155.510   337.920
19    19   112.390  132.490   279.690
20    20    98.940  136.050   272.100
21    21    88.890  133.000   266.000
22    22    90.150   39.080   255.750
23    23    76.990   15.000   242.450

### Individual Replay

In [43]:
model = gp.Model("DER_Individual_Replay")
model.setParam("MIPGap", 1e-5)
model.setParam(GRB.Param.PoolSearchMode, 2)
model.setParam(GRB.Param.PoolSolutions, 2)

x = model.addVars(I, T, vtype=GRB.CONTINUOUS, lb=0, name="x")
yp = model.addVars(I, T, S, vtype=GRB.CONTINUOUS, lb=0, name="yp") ; ym = model.addVars(I, T, S, vtype=GRB.CONTINUOUS, lb=0, name="ym") 
dp = model.addVars(I, T, S, vtype=GRB.CONTINUOUS, lb=0, name="dp") ; dm = model.addVars(I, T, S, vtype=GRB.CONTINUOUS, lb=0, name="dm") 
z = model.addVars(I, T + 1, S, vtype=GRB.CONTINUOUS, lb=0, name="z")
zc = model.addVars(I, T, S, vtype=GRB.CONTINUOUS, lb=0, name="zc") ; zd = model.addVars(I, T, S, vtype=GRB.CONTINUOUS, lb=0, name="zd")
phi1 = model.addVars(I, T, S, vtype=GRB.BINARY, name="phi1") ; phi2 = model.addVars(I, T, S, vtype=GRB.BINARY, name="phi2") 
phi3 = model.addVars(I, T, S, vtype=GRB.BINARY, name="phi3") ; phi4 = model.addVars(I, T, S, vtype=GRB.BINARY, name="phi4")
phi5 = model.addVars(I, T, S, vtype=GRB.BINARY, name="phi5") ; phi6 = model.addVars(I, T, S, vtype=GRB.BINARY, name="phi6") ; phi7 = model.addVars(I, T, S, vtype=GRB.BINARY, name="phi7")

zc0 = model.addVars(I, T, vtype=GRB.CONTINUOUS, name="zc0") ; zcR = model.addVars(I, T, vtype=GRB.CONTINUOUS, name="zcR")
zd0 = model.addVars(I, T, vtype=GRB.CONTINUOUS, name="zd0") ; zdR = model.addVars(I, T, vtype=GRB.CONTINUOUS, name="zdR")
zc2 = model.addVars(I, T, vtype=GRB.CONTINUOUS, name="zc2") ; zd2 = model.addVars(I, T, vtype=GRB.CONTINUOUS, name="zd2")

model.update()

obj = (
    gp.quicksum(P_DA[t] * x[i, t] for i in range(I) for t in range(T)) + 
    gp.quicksum((1/S) * (
        P_RT[t, s] * yp[i, t, s] - P_PN[t, s] * ym[i, t, s]
    ) for i in range(I) for t in range(T) for s in range(S)) +
    gp.quicksum(lambda_rep[t, s] * (
        gp.quicksum(dm[i, t, s] for i in range(I)) - gp.quicksum(dp[i, t, s] for i in range(I))
    ) for t in range(T) for s in range(S))
)
# model.setObjective(obj, GRB.MAXIMIZE)

epsilon = 1e-7
reg = gp.quicksum(x[i, t] * x[i, t] for i in range(I) for t in range(T))
regularized_obj = obj - epsilon * reg
model.setObjective(regularized_obj, GRB.MAXIMIZE)

for i, t, s in product(range(I), range(T), range(S)):
    # model.addConstr(zc[i, t, s] == zc0[i, t] + zcR[i, t] * R[i, t, s])
    # model.addConstr(zd[i, t, s] == zd0[i, t] + zdR[i, t] * R[i, t, s])
    # model.addConstr(zc[i, t, s] == zc0[i, t] + zcR[i, t] * P_RT[t, s])
    # model.addConstr(zd[i, t, s] == zd0[i, t] + zdR[i, t] * P_RT[t, s])
    # model.addConstr(zc[i, t, s] == zc0[i, t] + zcR[i, t] * P_PN[t, s])
    # model.addConstr(zd[i, t, s] == zd0[i, t] + zdR[i, t] * P_PN[t, s])
    model.addConstr(zc[i, t, s] == zc0[i, t] + zcR[i, t] * (P_RT[t, s] - P_DA[t]))
    model.addConstr(zd[i, t, s] == zd0[i, t] + zdR[i, t] * (P_RT[t, s] - P_DA[t]))
    # model.addConstr(zc[i, t, s] == zc0[i, t] + zcR[i, t] * (P_PN[t, s] - P_DA[t]))
    # model.addConstr(zd[i, t, s] == zd0[i, t] + zdR[i, t] * (P_PN[t, s] - P_DA[t]))
    # model.addConstr(zc[i, t, s] == zc0[i, t] + zcR[i, t] * R[i, t, s] + zc2[i, t] * P_RT[t, s])
    # model.addConstr(zd[i, t, s] == zd0[i, t] + zdR[i, t] * R[i, t, s] + zd2[i, t] * P_RT[t, s])
    # model.addConstr(zc[i, t, s] == zc0[i, t] + zcR[i, t] * R[i, t, s] + zc2[i, t] * P_PN[t, s])
    # model.addConstr(zd[i, t, s] == zd0[i, t] + zdR[i, t] * R[i, t, s] + zd2[i, t] * P_PN[t, s])
    # model.addConstr(zc[i, t, s] == zc0[i, t] + zcR[i, t] * R[i, t, s] + zc2[i, t] * (P_RT[t, s] - P_DA[t]))
    # model.addConstr(zd[i, t, s] == zd0[i, t] + zdR[i, t] * R[i, t, s] + zd2[i, t] * (P_RT[t, s] - P_DA[t]))

for i, t, s in product(range(I), range(T), range(S)):
    model.addConstr(R[i, t, s] - x[i, t] == yp[i, t, s] - ym[i, t, s] + dp[i, t, s] - dm[i, t, s] + zc[i, t, s] - zd[i, t, s])
    model.addConstr(R[i, t, s] + zd[i, t, s] >= yp[i, t, s] + dp[i, t, s] + zc[i, t, s])
    model.addConstr(zd[i, t, s] <= z[i, t, s]) ; model.addConstr(zc[i, t, s] <= K[i] - z[i, t, s]) ; model.addConstr(z[i, t, s] <= K[i])
    model.addConstr(z[i, t + 1, s] == z[i, t, s] + 0.9 * zc[i, t, s] - zd[i, t, s] / 0.9)
    
    model.addConstr(yp[i, t, s] <= M1 * phi1_hol[i, t, s]) ; model.addConstr(ym[i, t, s] <= M1 * (1 - phi1_hol[i, t, s]))
    model.addConstr(dp[i, t, s] <= M1 * phi2_hol[i, t, s]) ; model.addConstr(dm[i, t, s] <= M1 * (1 - phi2_hol[i, t, s]))
    model.addConstr(yp[i, t, s] <= M1 * phi3_hol[i, t, s]) ; model.addConstr(dm[i, t, s] <= M1 * (1 - phi3_hol[i, t, s]))
    model.addConstr(ym[i, t, s] <= M1 * phi4_hol[i, t, s]) ; model.addConstr(dp[i, t, s] <= M1 * (1 - phi4_hol[i, t, s]))
    model.addConstr(ym[i, t, s] <= M1 * phi5_hol[i, t, s]) ; model.addConstr(zc[i, t, s] <= M1 * (1 - phi5_hol[i, t, s]))
    model.addConstr(dm[i, t, s] <= M1 * phi6_hol[i, t, s]) ; model.addConstr(zc[i, t, s] <= M1 * (1 - phi6_hol[i, t, s]))
    model.addConstr(zc[i, t, s] <= M1 * phi7_hol[i, t, s]) ; model.addConstr(zd[i, t, s] <= M1 * (1 - phi7_hol[i, t, s]))
    
    # model.addConstr(yp[i, t, s] <= M1 * phi1[i, t, s]) ; model.addConstr(ym[i, t, s] <= M1 * (1 - phi1[i, t, s]))
    # model.addConstr(dp[i, t, s] <= M1 * phi2[i, t, s]) ; model.addConstr(dm[i, t, s] <= M1 * (1 - phi2[i, t, s]))
    # model.addConstr(yp[i, t, s] <= M1 * phi3[i, t, s]) ; model.addConstr(dm[i, t, s] <= M1 * (1 - phi3[i, t, s]))
    # model.addConstr(ym[i, t, s] <= M1 * phi4[i, t, s]) ; model.addConstr(dp[i, t, s] <= M1 * (1 - phi4[i, t, s]))
    # model.addConstr(ym[i, t, s] <= M1 * phi5[i, t, s]) ; model.addConstr(zc[i, t, s] <= M1 * (1 - phi5[i, t, s]))
    # model.addConstr(dm[i, t, s] <= M1 * phi6[i, t, s]) ; model.addConstr(zc[i, t, s] <= M1 * (1 - phi6[i, t, s]))
    # model.addConstr(zc[i, t, s] <= M1 * phi7[i, t, s]) ; model.addConstr(zd[i, t, s] <= M1 * (1 - phi7[i, t, s]))

for i, s in product(range(I), range(S)): 
    model.addConstr(z[i, 0, s] == K0[i])
    # model.addConstr(dp[i,12,s] == 0) ; model.addConstr(dp[i,13,s] == 0) ; model.addConstr(dp[i,15,s] == 0)
    # model.addConstr(dm[i,12,s] == 0) ; model.addConstr(dm[i,13,s] == 0) ; model.addConstr(dm[i,15,s] == 0)

model.optimize()

if model.status == GRB.OPTIMAL:
    num_solutions = model.SolCount
    print(f"\n--- Solution Pool Analysis ---")
    print(f"Found {num_solutions} solutions in the pool.")

    if num_solutions > 1:
        best_obj = model.objVal
        print(f"Best objective value: {best_obj:.8f}\n")

        for i in range(num_solutions):
            model.setParam(GRB.Param.SolutionNumber, i)
            pool_obj = model.PoolObjVal
            diff = best_obj - pool_obj
            
            print(f"Solution {i}: Objective = {pool_obj},  Difference from best = {diff}")

    model.setParam(GRB.Param.SolutionNumber, 0)
    
    print(f"Optimal solution found! Objective value: {model.objVal}")
else:
    print("No optimal solution found.")

x_re = np.array([[x[i, t].X for t in range(T)] for i in range(I)])
yp_re = np.array([[[yp[i, t, s].X for s in range(S)] for t in range(T)] for i in range(I)]) ; ym_re = np.array([[[ym[i, t, s].X for s in range(S)] for t in range(T)] for i in range(I)])
dp_re = np.array([[[dp[i, t, s].X for s in range(S)] for t in range(T)] for i in range(I)]) ; dm_re = np.array([[[dm[i, t, s].X for s in range(S)] for t in range(T)] for i in range(I)])
z_re = np.array([[[z[i, t, s].X for s in range(S)] for t in range(T+1)] for i in range(I)])
zc_re = np.array([[[zc[i, t, s].X for s in range(S)] for t in range(T)] for i in range(I)]) ; zd_re = np.array([[[zd[i, t, s].X for s in range(S)] for t in range(T)] for i in range(I)])
zc0_re = np.array([[zc0[i, t].X for t in range(T)] for i in range(I)]) ; zd0_re = np.array([[zd0[i, t].X for t in range(T)] for i in range(I)])
zcR_re = np.array([[zcR[i, t].X for t in range(T)] for i in range(I)]) ; zdR_re = np.array([[zdR[i, t].X for t in range(T)] for i in range(I)])
OBJ_RE = model.objVal

Set parameter MIPGap to value 1e-05
Set parameter PoolSearchMode to value 2
Set parameter PoolSolutions to value 2
Gurobi Optimizer version 12.0.2 build v12.0.2rc0 (win64 - Windows 11.0 (26100.2))

CPU model: 13th Gen Intel(R) Core(TM) i9-13900K, instruction set [SSE2|AVX|AVX2]
Thread count: 24 physical cores, 32 logical processors, using up to 32 threads

Non-default parameters:
MIPGap  1e-05
PoolSolutions  2
PoolSearchMode  2

Optimize a model with 52900 rows, 34540 columns and 96100 nonzeros
Model fingerprint: 0xde914764
Model has 120 quadratic objective terms
Variable types: 17740 continuous, 16800 integer (16800 binary)
Coefficient statistics:
  Matrix range     [5e-03, 2e+02]
  Objective range  [6e-01, 2e+02]
  QObjective range [2e-07, 2e-07]
  Bounds range     [1e+00, 1e+00]
  RHS range        [1e-03, 8e+02]
Presolve removed 51116 rows and 15434 columns
Presolve time: 0.03s
Presolved: 1784 rows, 19106 columns, 6567 nonzeros
Presolved model has 91 quadratic objective terms
Variable types: 2306 continuous, 16800 integer (16800 binary)
Found heuristic solution: objective 1715226.3188

Root relaxation: objective 1.715226e+06, 3769 iterations, 0.04 seconds (0.04 work units)

    Nodes    |    Current Node    |     Objective Bounds      |     Work
 Expl Unexpl |  Obj  Depth IntInf | Incumbent    BestBd   Gap | It/Node Time

     0     0          -    0      1715226.32 1715226.32  0.00%     -    0s

Optimal solution found at node 0 - now completing solution pool...

    Nodes    |    Current Node    |      Pool Obj. Bounds     |     Work
             |                    |   Worst                   |
 Expl Unexpl |  Obj  Depth IntInf | Incumbent    BestBd   Gap | It/Node Time

     0     0          -    0               - 1715226.32      -     -    0s
     0     0          -    0               - 1715226.32      -     -    0s
     0     2          -    0               - 1715226.32      -     -    0s

Explored 3 nodes (3769 simplex iterations) in 0.16 seconds (0.15 work units)
Thread count was 32 (of 32 available processors)

Solution count 2: 1.71523e+06 1.71523e+06
No other solutions better than 1.71523e+06

Optimal solution found (tolerance 1.00e-05)
Best objective 1.715226318753e+06, best bound 1.715226318753e+06, gap 0.0000%

--- Solution Pool Analysis ---
Found 2 solutions in the pool.
Best objective value: 1715226.31875250

Solution 0: Objective = 1715226.3187525035,  Difference from best = 0.0
Solution 1: Objective = 1715226.3187426918,  Difference from best = 9.81171615421772e-06
Optimal solution found! Objective value: 1715226.3187525035

In [44]:
header = (f"{'t':>2} | {'R':>8} {'x':>8} {'y+':>8} {'y-':>8} {'d+':>8} {'d-':>8} {'zc':>8} {'zd':>8} {'z':>8}\n" + "-" * 90)
print("\n[REPLAY]") ; print(header)
for t in range(9,20):
    R_avg = np.mean([R[:, t, s].sum() for s in range(S)]) ; x_sum = x_re[:, t].sum()
    yp_avg = np.mean([yp_re[:, t, s].sum() for s in range(S)]) ; ym_avg = np.mean([ym_re[:, t, s].sum() for s in range(S)])
    dp_avg = np.mean([dp_re[:, t, s].sum() for s in range(S)]) ; dm_avg = np.mean([dm_re[:, t, s].sum() for s in range(S)])
    zc_avg = np.mean([zc_re[:, t, s].sum() for s in range(S)]) ; zd_avg = np.mean([zd_re[:, t, s].sum() for s in range(S)]) ; z_avg = np.mean([z_re[:, t, s].sum() for s in range(S)])
    print(f"{t:>2} | {R_avg:>8.2f} {x_sum:>8.2f} {yp_avg:>8.2f} {ym_avg:>8.2f} {dp_avg:>8.2f} {dm_avg:>8.2f} {zc_avg:>8.2f} {zd_avg:>8.2f} {z_avg:>8.2f}")

print("\n[HOLISTIC]") ; print(header)
for t in range(9,20):
    R_avg = np.mean([R[:, t, s].sum() for s in range(S)]) ; x_sum = x_hol[:, t].sum()
    yp_avg = np.mean([yp_hol[:, t, s].sum() for s in range(S)]) ; ym_avg = np.mean([ym_hol[:, t, s].sum() for s in range(S)])
    dp_avg = np.mean([dp_hol[:, t, s].sum() for s in range(S)]) ; dm_avg = np.mean([dm_hol[:, t, s].sum() for s in range(S)])
    zc_avg = np.mean([zc_hol[:, t, s].sum() for s in range(S)]) ; zd_avg = np.mean([zd_hol[:, t, s].sum() for s in range(S)]) ; z_avg = np.mean([z_hol[:, t, s].sum() for s in range(S)])
    print(f"{t:>2} | {R_avg:>8.2f} {x_sum:>8.2f} {yp_avg:>8.2f} {ym_avg:>8.2f} {dp_avg:>8.2f} {dm_avg:>8.2f} {zc_avg:>8.2f} {zd_avg:>8.2f} {z_avg:>8.2f}")

[REPLAY]
 t |        R        x       y+       y-       d+       d-       zc       zd        z
------------------------------------------------------------------------------------------
 9 |   185.31   113.96     1.82     0.00   131.29   110.10    48.34     0.00    14.31
10 |   445.25   220.98    57.00     0.00   246.14   187.49   108.62     0.00    57.82
11 |   652.06   255.20   214.58     0.00   210.06   183.50   155.71     0.00   155.58
12 |   860.69     0.00   752.36     0.00     0.00     0.00   108.33     0.00   295.72
13 |  1397.66     0.00  1556.27     0.00     0.00     0.00     0.00   158.61   393.22
14 |  1338.06   912.25   115.61     4.10   572.65   522.66   264.31     0.00   216.98
15 |   804.05     0.00  1213.42     0.00     0.00     0.00     0.00   409.38   454.87
16 |   756.56   520.42    78.64     1.13   266.73   108.10     0.00     0.00    -0.00
17 |   738.45     0.00   738.45     0.00     0.00     0.00     0.00     0.00    -0.00
18 |   493.98   261.08   169.58     0.00   121.43    58.10     0.00     0.00     0.00
19 |   399.71   277.41    49.76     6.25   130.96    52.17     0.00     0.00     0.00

[HOLISTIC]
 t |        R        x       y+       y-       d+       d-       zc       zd        z
------------------------------------------------------------------------------------------
 9 |   185.31   113.96    29.72     6.70   103.39   103.39    48.34     0.00    14.31
10 |   445.25   220.98   117.68     2.04   185.45   185.45   108.62     0.00    57.82
11 |   652.06   255.20   241.14     0.00   183.50   183.50   155.71     0.00   155.58
12 |   860.69     0.00   752.36     0.00     0.00     0.00   108.33     0.00   295.72
13 |  1397.66     0.00  1556.27     0.00     0.00     0.00     0.00   158.61   393.22
14 |  1338.06   914.59   179.83    20.67   508.43   508.43   264.31     0.00   216.98
15 |   804.05     0.00  1213.42     0.00     0.00     0.00     0.00   409.38   454.87
16 |   756.56   538.86   223.64     5.94   160.45   160.45     0.00     0.00     0.00
17 |   738.45     0.00   738.45     0.00     0.00     0.00     0.00     0.00     0.00
18 |   493.98   296.43   197.55     0.00    62.36    62.36     0.00     0.00     0.00
19 |   399.71   280.63   125.65     6.57    52.20    52.20     0.00     0.00     0.00

In [45]:
# print("\n=== 모든 LDR 계수 (i, t별) ===")
# print("Individual | Time | Variable | 상수항     | R계수    ")
# print("-" * 50)

# for t in range(T):
#     for i in range(I):
#         print(f"{i:10d} | {t:4d} | zc       | {zc0_re[i,t]:8.4f} | {zcR_re[i,t]:7.4f}")
#         print(f"{i:10d} | {t:4d} | zd       | {zd0_re[i,t]:8.4f} | {zdR_re[i,t]:7.4f}")
#         print(f"{i:10d} | {t:4d} | x (1st)  | {x_re[i,t]:8.4f} |    -    ")
#         print("-" * 50)

In [46]:
print("="*50) ; print("AGGREGATOR LOSS ANALYSIS") ; print("="*50)

total_losses = []

for t in range(T):
    scenario_losses = []
    
    for s in range(S):
        total_supply = np.sum(dp_re[:, t, s])
        total_demand = np.sum(dm_re[:, t, s])
        
        if total_supply > total_demand:
            excess_supply = total_supply - total_demand
            # loss = excess * (-lambda_rep[t, s]*S - P_RT[t, s])
            # loss = excess * (P_RT[t, s])
            loss = excess_supply * (P_RT[t, s] - (-lambda_rep[t, s]*S))
        else:
            excess = total_demand - total_supply
            # loss = excess * (P_PN[t, s] - (-lambda_rep[t,s]*S))
            # loss = excess * (P_RT[t, s])
            loss = excess * ((-lambda_rep[t,s]*S) - P_RT[t, s])
        
        scenario_losses.append(loss)
    
    avg_loss = np.mean(scenario_losses)
    total_losses.append(avg_loss)
    # print(f"t={t} Average Loss: {avg_loss:.2f}")

overall_avg_loss = np.mean(total_losses)
total_loss = np.sum(total_losses)

print("[SUMMARY]")
print("Individual Participation Profit", OBJ_IND)
print("Expected Replay Profit", OBJ_RE)
print(f"Total loss across all time periods: {total_loss:.2f}")
print("Realized Profit", OBJ_RE + total_loss)
print("Holistic Profit", OBJ_HOL)

==================================================
AGGREGATOR LOSS ANALYSIS
==================================================
[SUMMARY]
Individual Participation Profit 1632097.9322771467
Expected Replay Profit 1715226.3187525035
Total loss across all time periods: -20342.50
Realized Profit 1694883.816907601
Holistic Profit 1689908.8515537635